package constants

/**
  * Created by Fincash on 24-02-2017.
  */
trait CNDConstants {
  val NATIONALITY = "NATIONALITY"
  val PIN = "PIN"
  val STATE = "STATE"
  val CITY = "CITY"
  val COUNTRY = "COUNTRY"
  val SECURITY_SECTOR_TYPE = "SECURITYSECTORTYPE"
  val SECURITY_SECTOR = "SECURITYSECTOR"
  val OCCUPATION = "OCCUPATION"
  val MARITAL_STATUS = "MARITALSTATUS"
  val ADDRESS_TYPE = "ADDRESSTYPE"
  val ACCOUNT_TYPE = "ACCOUNTTYPE"
  val DOCUMENT_TYPE = "DOCUMENTTYPE"
  val DISTRICT = "DISTRICT"
  val RELATIONSHIP = "RELATIONSHIP"
  val TAX_STATUS = "TAXSTATUS"
  val INCOME_SLAB = "INCOMESLAB"
  val WEALTH_SOURCE = "WEALTHSOURCE"
  val ADDRESS_PROOF = "ADDRESSPROOF"
  val BANK_PROOF = "BANKDOC"
  val ID_PROOF = "IDPROOF"
  val PHOTO_PROOF = "PHOTOPROOF"
  val SIGNATURE_PROOF = "SIGNATUREPROOF"
  val TAX_STATUS_INDIVIDUAL =  975L
  val TAX_STATUS_ON_BEHALF_MINOR =  976L
  val TAX_STATUS_HUF =  977L
  val TAX_STATUS_COMPANY =  978L
  val TAX_STATUS_AOP =  979L
  val TAX_STATUS_PARTNERSHIP_FIRM =  980L
  val TAX_STATUS_TRUST =  981L
  val TAX_STATUS_OTHERS =  982L
  val TAX_STATUS_DIF =  983L
  val TAX_STATUS_NRE =  984L
  val TAX_STATUS_FII =  985L
  val TAX_STATUS_NRO =  986L
  val TAX_STATUS_LLP =  987L

}
