package constants

import scala.collection.mutable

/**
  * Created by fincash on 16-02-2017.
  */
trait OrderConstants {

  final val BUYSELL_BUY_FRESH = "BF"
  final val BUYSELL_BUY_ADDITIONAL = "BA"
  final val BUYSELL_SELL = "R"
  final val BUYSELL_SWP = "SW"
  final val BUYSELL_STP = "ST"
  final val BUYSELL_SWITCH_IN = "SI"
  final val BUYSELL_SWITCH_OUT = "SO"
  final val DP_TRANSACTION = "P"
  final val NET_BANKING_PAYMENT_MODE = "N"

  final val PHYSICAL_MODE = "P"
  final val DEMAT_MODE = "D"

  final val BSE_TRANSACTION_MODE = "BSE"
  final val RELIANCE_TRANSACTION_MODE = "REL"
  final val BIRLA_TRNSACTION_MODE = "BSL"

  final val BUYSELL_BUY = "P"
  final val FRESH = "F"
  final val FRESH_VALUE = "FRESH"
  final val ACKNOWLEDGE_FRESH_VALUE = "Fresh"
  final val ADDITIONAL = "A"
  final val ADDITIONAL_VALUE = "ADDITIONAL"
  final val ACKNOWLEDGE_ADDITIONAL_VALUE = "Additional"

  // Credit debit
  final val CREDIT = "C"
  final val DEBIT = "D"

  // Reliance Redemption
  final val REDEMPTION_PARTIAL = "P"
  final val ACKNOWLEDGE_REDEMPTION_PARTIAL_VALUE = "Partial"
  final val REDEMPTION_FULL = "F"
  final val ACKNOWLEDGE_REDEMPTION_FULL_VALUE = "Full"

  final val AMOUNTUNIT_AMOUNT = "A"
  final val AMOUNTUNIT_UNIT = "U"

  // Order Transaction Modes
  final val BSE = "BSE"
  final val RTA = "RTA"

  //SIP Rolling Frequency
  final val ROLLING_FREQUENCY = 1

  //order state constants
  final val ORDER_CREATED = 1L
  final val PLACED_AT_EXCHANGE = 2L
  final val ORDER_AWAITING_PAYMENT = 3L
  final val PAYMENT_APPROVED = 4L
  final val ORDER_REJECTED = 5L
  final val ORDER_COMPLETED = 6L
  final val ORDER_CANCELLED = 7L
  final val MAIN_ORDER_INITIATED = 8L
  final val MAIN_ORDER_IN_PROCESS = 9L
  final val PLACED_AT_EXCHANGE_PG = 10L
  final val MAIN_ORDER_PARTIAL_COMPLETE = 11L
  final val MAIN_ORDER_COMPLETE = 12L
  final val ORDER_FAILED = 13L
  final val ORDER_REVERSED = 14L
  final val REDEMPTION_APPROVED = 15L
  final val PLACED_AT_AMC = 16L
  final val ORDER_TO_BE_PLACED_LATER = 17L

  final val ORDER_STATUS_FAILURE = 1L
  final val ORDER_STATUS_SUCCESS = 0L
  final val ORDER_CONNECTIVITY_FAILURE = 2L
  final val ORDER_PAYMENT_NOT_FOUND = 1L

  final val L_ONE_ORDER = "L1"
  final val L_ZERO_ORDER = "L0"

  final val BSE_PAYMENT_NOT_INITIATED = "PAYMENT NOT INITIATED FOR GIVEN ORDER"
  final val BSE_AWAITING_FUNDS_CONFIRMATION = "AWAITING FOR FUNDS CONFIRMATION"
  final val BSE_PAYMENT_APPROVED = "APPROVED"
  final val BSE_PAYMENT_REJECTED = "REJECTED"

  final val FOLIO_NO_KEY = "FOLIO_NO"
  final val BSE_SCHEME_CODE_KEY = "BSE_SCHEME_CODE"
  final val ORDER_CANCEL_CUT_OFF_KEY = "ORDER_CANCEL_CUT_OFF"
  final val ORDER_APPROX_ALLOT_KEY = "APPROX_ALLOTMENT_DATE"
  final val ORDER_PAY_CUT_OFF_KEY = "PAYMENT_CUT_OFF"
  final val BSE_STD_CUTOFF_KEY = "BSE_STD_CUTOFF"
  final val BSE_PAY_START_CUTOFF_KEY = "BSE_PAY_START_CUTOFF"
  final val BSE_PAY_CUTOFF_KEY = "BSE_PAY_CUTOFF"
  final val ORDER_PROD_SOLN_ID_KEY = "PRODUCT_SOLUTION_ID"
  final val ORDER_PROD_SOLN_NAME_KEY = "PRODUCT_SOLUTION_NAME"
  final val PAYMENT_FALLBACK_BASE_URL_KEY = "PAYMENT_FALLBACK_BASE_URL"
  final val SIP_START_DATE_KEY = "SIP_START_DATE"

  final val STATE_CHANGE_NOT_ALLOWED = "Order State Change Not Allowed"
  final val STATE_CHANGED_SUCCESSFULLY = "State Updated Successfully"
}

object OrderConstants extends OrderConstants with DBConstants {

  val FREQUENCY_MAP = mutable.HashMap[String, String]()
  FREQUENCY_MAP.+=(MONTHLY_FREQUENCY -> MONTHLY_FREQUENCY_VALUE)
  FREQUENCY_MAP.+=(QUATERLY_FREQUENCY -> QUATERLY_FREQUENCY_VALUE)
  FREQUENCY_MAP.+=(ANNUALLY_FREQUENCY -> ANNUALLY_FREQUENCY_VALUE)
  FREQUENCY_MAP.+=(SEMI_ANNUALLY_FREQUENCY -> SEMI_ANNUALLY_FREQUENCY_VALUE)

  val BUY_SELL_TYPEMAP = mutable.HashMap[String, String]()
  BUY_SELL_TYPEMAP.+=(FRESH -> FRESH_VALUE)
  BUY_SELL_TYPEMAP.+=(ADDITIONAL -> ADDITIONAL_VALUE)
  BUY_SELL_TYPEMAP.+=(REDEMPTION_FULL -> FRESH_VALUE)
  BUY_SELL_TYPEMAP.+=(REDEMPTION_PARTIAL -> FRESH_VALUE)

  val REDEMPTION_BUY_SELL_TYPE_MAP = mutable.HashMap[String,String]()
  REDEMPTION_BUY_SELL_TYPE_MAP.+=(REDEMPTION_FULL -> ACKNOWLEDGE_REDEMPTION_FULL_VALUE)
  REDEMPTION_BUY_SELL_TYPE_MAP.+=(REDEMPTION_PARTIAL -> ACKNOWLEDGE_REDEMPTION_PARTIAL_VALUE)

  val PURCHASE_BUY_SELL_TYPE_MAP = mutable.HashMap[String,String]()
  PURCHASE_BUY_SELL_TYPE_MAP.+=(FRESH -> ACKNOWLEDGE_FRESH_VALUE)
  PURCHASE_BUY_SELL_TYPE_MAP.+=(ADDITIONAL -> ACKNOWLEDGE_ADDITIONAL_VALUE)

  val ORDER_STATE_MAP = mutable.HashMap[String, Long]()
  ORDER_STATE_MAP.+=(BSE_PAYMENT_NOT_INITIATED -> PLACED_AT_EXCHANGE)
  ORDER_STATE_MAP.+=(BSE_AWAITING_FUNDS_CONFIRMATION -> ORDER_AWAITING_PAYMENT)
  ORDER_STATE_MAP.+=(BSE_PAYMENT_APPROVED -> PAYMENT_APPROVED)
  ORDER_STATE_MAP.+=(BSE_PAYMENT_REJECTED -> ORDER_CANCELLED)


}
