INSERT INTO FCOSTM (OSTMNAME, OSTMACTIVE, OSTMDESCRIP, OSTMDISPLAYNAME, CREATEDATE, MODIFYDATE, CREATEDBY, LASTMODIFIEDBY)
VALUES
  ('ORDER_PLACED_BSE_PG', 'Y', 'Placed at Exchange', 'Placed at Exchange(BSE)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,
   'SYSTEM', 'SYSTEM');
INSERT INTO FCOSTM (OSTMNAME, OSTMACTIVE, OSTMDESCRIP, OSTMDISPLAYNAME, CREATEDATE, MODIFYDATE, CREATEDBY, LASTMODIFIEDBY)
VALUES ('MAIN_ORDER_PARTIAL_COMPLETE', 'Y', 'Partially Completed', 'Partially Completed', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM');
INSERT INTO FCOSTM (OSTMNAME, OSTMACTIVE, OSTMDESCRIP, OSTMDISPLAYNAME, CREATEDATE, MODIFYDATE, CREATEDBY, LASTMODIFIEDBY)
VALUES
  ('MAIN_ORDER_COMPLETE', 'Y', 'Order Completed', 'Order Completed', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM',
   'SYSTEM');
INSERT INTO FCACT (ACTCONSTANTNAME, ACTCONSTANTVALUE, ACTACTIVE, CREATEDATE, MODIFYDATE, CREATEDBY, LASTMODIFIEDBY)
VALUES ('ISIP_AMC', '2,3,4,5,6,7,8,11,12,13,14,15,16,17,18,19,20,21,22,23,25,28,31,35,36,37', 'Y', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP, 'admin', 'admin');
INSERT INTO FCACT (ACTCONSTANTNAME, ACTCONSTANTVALUE, ACTACTIVE, CREATEDATE, MODIFYDATE, CREATEDBY, LASTMODIFIEDBY)
VALUES ('BSE_STD_CUTOFF', '14:25:00', 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');

SET FOREIGN_KEY_CHECKS = 0;

/* Drop Tables */

DROP TABLE IF EXISTS `FCHOLI` CASCADE;

/* Create Tables */

CREATE TABLE `FCHOLI`
(
  `HOLIRFNUM`         BIGINT       NOT NULL AUTO_INCREMENT,
  `HOLINAME`          VARCHAR(128) NOT NULL,
  `HOLIDATE`          DATE         NOT NULL,
  `HOLIMARKETSEGMENT` CHAR(10)     NULL
  COMMENT 'Debt/Equity/Bank/AMC Name/RTA',
  `HOLIAMCRFNUM`      BIGINT       NULL,
  `CREATEDATE`        TIMESTAMP    NOT NULL DEFAULT '2017-01-01 00:00:01',
  `MODIFYDATE`        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATEDBY`         CHAR(64)     NOT NULL,
  `LASTMODIFIEDBY`    CHAR(64)     NOT NULL,
  CONSTRAINT `PK_FCHOLI` PRIMARY KEY (`HOLIRFNUM` ASC)
)
  COMMENT = 'FCHOLI: Holiday Master Table';

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `FCHOLI`
  ADD CONSTRAINT `HOLI_DATE_SEGMENT_UNQ` UNIQUE (`HOLIDATE` ASC, `HOLIMARKETSEGMENT` ASC, `HOLIAMCRFNUM` ASC);

SET FOREIGN_KEY_CHECKS = 1;

INSERT INTO `FCHOLI` (`HOLIRFNUM`, `HOLINAME`, `HOLIDATE`, `HOLIMARKETSEGMENT`, `CREATEDATE`, `MODIFYDATE`, `CREATEDBY`, `LASTMODIFIEDBY`)
VALUES (1, 'Republic Day', '2017-01-26', 'BANK', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');
INSERT INTO `FCHOLI` (`HOLIRFNUM`, `HOLINAME`, `HOLIDATE`, `HOLIMARKETSEGMENT`, `CREATEDATE`, `MODIFYDATE`, `CREATEDBY`, `LASTMODIFIEDBY`)
VALUES (2, 'Republic Day', '2017-01-26', 'EQUITY', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');
INSERT INTO `FCHOLI` (`HOLIRFNUM`, `HOLINAME`, `HOLIDATE`, `HOLIMARKETSEGMENT`, `CREATEDATE`, `MODIFYDATE`, `CREATEDBY`, `LASTMODIFIEDBY`)
VALUES (3, 'Republic Day', '2017-01-26', 'DEBT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');
INSERT INTO `FCHOLI` (`HOLIRFNUM`, `HOLINAME`, `HOLIDATE`, `HOLIMARKETSEGMENT`, `CREATEDATE`, `MODIFYDATE`, `CREATEDBY`, `LASTMODIFIEDBY`)
VALUES
  (4, 'Municipal Corporation Elections', '2017-02-21', 'BANK', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');
INSERT INTO `FCHOLI` (`HOLIRFNUM`, `HOLINAME`, `HOLIDATE`, `HOLIMARKETSEGMENT`, `CREATEDATE`, `MODIFYDATE`, `CREATEDBY`, `LASTMODIFIEDBY`)
VALUES (5, 'Mahashivratri', '2017-02-24', 'BANK', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');
INSERT INTO `FCHOLI` (`HOLIRFNUM`, `HOLINAME`, `HOLIDATE`, `HOLIMARKETSEGMENT`, `CREATEDATE`, `MODIFYDATE`, `CREATEDBY`, `LASTMODIFIEDBY`)
VALUES (6, 'Mahashivratri', '2017-02-24', 'EQUITY', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');
INSERT INTO `FCHOLI` (`HOLIRFNUM`, `HOLINAME`, `HOLIDATE`, `HOLIMARKETSEGMENT`, `CREATEDATE`, `MODIFYDATE`, `CREATEDBY`, `LASTMODIFIEDBY`)
VALUES (7, 'Mahashivratri', '2017-02-24', 'DEBT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');
INSERT INTO `FCHOLI` (`HOLIRFNUM`, `HOLINAME`, `HOLIDATE`, `HOLIMARKETSEGMENT`, `CREATEDATE`, `MODIFYDATE`, `CREATEDBY`, `LASTMODIFIEDBY`)
VALUES (8, 'Holi', '2017-03-13', 'BANK', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');
INSERT INTO `FCHOLI` (`HOLIRFNUM`, `HOLINAME`, `HOLIDATE`, `HOLIMARKETSEGMENT`, `CREATEDATE`, `MODIFYDATE`, `CREATEDBY`, `LASTMODIFIEDBY`)
VALUES (9, 'Holi', '2017-03-13', 'EQUITY', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');
INSERT INTO `FCHOLI` (`HOLIRFNUM`, `HOLINAME`, `HOLIDATE`, `HOLIMARKETSEGMENT`, `CREATEDATE`, `MODIFYDATE`, `CREATEDBY`, `LASTMODIFIEDBY`)
VALUES (10, 'Holi', '2017-03-13', 'DEBT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');
INSERT INTO `FCHOLI` (`HOLIRFNUM`, `HOLINAME`, `HOLIDATE`, `HOLIMARKETSEGMENT`, `CREATEDATE`, `MODIFYDATE`, `CREATEDBY`, `LASTMODIFIEDBY`)
VALUES (11, 'Gudhi Padwa', '2017-03-28', 'BANK', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');
INSERT INTO `FCHOLI` (`HOLIRFNUM`, `HOLINAME`, `HOLIDATE`, `HOLIMARKETSEGMENT`, `CREATEDATE`, `MODIFYDATE`, `CREATEDBY`, `LASTMODIFIEDBY`)
VALUES (12, 'Gudhi Padwa', '2017-03-28', 'DEBT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');
INSERT INTO `FCHOLI` (`HOLIRFNUM`, `HOLINAME`, `HOLIDATE`, `HOLIMARKETSEGMENT`, `CREATEDATE`, `MODIFYDATE`, `CREATEDBY`, `LASTMODIFIEDBY`)
VALUES (13, 'Annual closing of Accounts of Commercial and Co-operative Banks', '2017-04-01', 'BANK', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP, 'admin', 'admin');
INSERT INTO `FCHOLI` (`HOLIRFNUM`, `HOLINAME`, `HOLIDATE`, `HOLIMARKETSEGMENT`, `CREATEDATE`, `MODIFYDATE`, `CREATEDBY`, `LASTMODIFIEDBY`)
VALUES (14, 'Ram Navami', '2017-04-04', 'BANK', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');
INSERT INTO `FCHOLI` (`HOLIRFNUM`, `HOLINAME`, `HOLIDATE`, `HOLIMARKETSEGMENT`, `CREATEDATE`, `MODIFYDATE`, `CREATEDBY`, `LASTMODIFIEDBY`)
VALUES (15, 'Ram Navami', '2017-04-04', 'DEBT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');
INSERT INTO `FCHOLI` (`HOLIRFNUM`, `HOLINAME`, `HOLIDATE`, `HOLIMARKETSEGMENT`, `CREATEDATE`, `MODIFYDATE`, `CREATEDBY`, `LASTMODIFIEDBY`)
VALUES (16, 'Ram Navami', '2017-04-04', 'EQUITY', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');
INSERT INTO `FCHOLI` (`HOLIRFNUM`, `HOLINAME`, `HOLIDATE`, `HOLIMARKETSEGMENT`, `CREATEDATE`, `MODIFYDATE`, `CREATEDBY`, `LASTMODIFIEDBY`)
VALUES
  (17, 'Dr.Baba Saheb Ambedkar Jayanti and Good Friday', '2017-04-14', 'BANK', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,
   'admin', 'admin');
INSERT INTO `FCHOLI` (`HOLIRFNUM`, `HOLINAME`, `HOLIDATE`, `HOLIMARKETSEGMENT`, `CREATEDATE`, `MODIFYDATE`, `CREATEDBY`, `LASTMODIFIEDBY`)
VALUES
  (18, 'Dr.Baba Saheb Ambedkar Jayanti and Good Friday', '2017-04-14', 'DEBT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,
   'admin', 'admin');
INSERT INTO `FCHOLI` (`HOLIRFNUM`, `HOLINAME`, `HOLIDATE`, `HOLIMARKETSEGMENT`, `CREATEDATE`, `MODIFYDATE`, `CREATEDBY`, `LASTMODIFIEDBY`)
VALUES
  (19, 'Dr.Baba Saheb Ambedkar Jayanti and Good Friday', '2017-04-14', 'EQUITY', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,
   'admin', 'admin');
INSERT INTO `FCHOLI` (`HOLIRFNUM`, `HOLINAME`, `HOLIDATE`, `HOLIMARKETSEGMENT`, `CREATEDATE`, `MODIFYDATE`, `CREATEDBY`, `LASTMODIFIEDBY`)
VALUES (20, 'Maharashtra Day', '2017-05-01', 'BANK', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');
INSERT INTO `FCHOLI` (`HOLIRFNUM`, `HOLINAME`, `HOLIDATE`, `HOLIMARKETSEGMENT`, `CREATEDATE`, `MODIFYDATE`, `CREATEDBY`, `LASTMODIFIEDBY`)
VALUES (21, 'Maharashtra Day', '2017-05-01', 'DEBT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');
INSERT INTO `FCHOLI` (`HOLIRFNUM`, `HOLINAME`, `HOLIDATE`, `HOLIMARKETSEGMENT`, `CREATEDATE`, `MODIFYDATE`, `CREATEDBY`, `LASTMODIFIEDBY`)
VALUES (22, 'Maharashtra Day', '2017-05-01', 'EQUITY', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');
INSERT INTO `FCHOLI` (`HOLIRFNUM`, `HOLINAME`, `HOLIDATE`, `HOLIMARKETSEGMENT`, `CREATEDATE`, `MODIFYDATE`, `CREATEDBY`, `LASTMODIFIEDBY`)
VALUES (23, 'Buddha Pournima', '2017-05-10', 'BANK', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');
INSERT INTO `FCHOLI` (`HOLIRFNUM`, `HOLINAME`, `HOLIDATE`, `HOLIMARKETSEGMENT`, `CREATEDATE`, `MODIFYDATE`, `CREATEDBY`, `LASTMODIFIEDBY`)
VALUES (24, 'Buddha Pournima', '2017-05-10', 'DEBT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');
INSERT INTO `FCHOLI` (`HOLIRFNUM`, `HOLINAME`, `HOLIDATE`, `HOLIMARKETSEGMENT`, `CREATEDATE`, `MODIFYDATE`, `CREATEDBY`, `LASTMODIFIEDBY`)
VALUES (25, 'Id-Ul-Fitr (Ramzan Id)', '2017-06-26', 'BANK', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');
INSERT INTO `FCHOLI` (`HOLIRFNUM`, `HOLINAME`, `HOLIDATE`, `HOLIMARKETSEGMENT`, `CREATEDATE`, `MODIFYDATE`, `CREATEDBY`, `LASTMODIFIEDBY`)
VALUES (26, 'Id-Ul-Fitr (Ramzan Id)', '2017-06-26', 'DEBT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');
INSERT INTO `FCHOLI` (`HOLIRFNUM`, `HOLINAME`, `HOLIDATE`, `HOLIMARKETSEGMENT`, `CREATEDATE`, `MODIFYDATE`, `CREATEDBY`, `LASTMODIFIEDBY`)
VALUES (27, 'Id-Ul-Fitr (Ramzan Id)', '2017-06-26', 'EQUITY', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');
INSERT INTO `FCHOLI` (`HOLIRFNUM`, `HOLINAME`, `HOLIDATE`, `HOLIMARKETSEGMENT`, `CREATEDATE`, `MODIFYDATE`, `CREATEDBY`, `LASTMODIFIEDBY`)
VALUES (28, 'Annual Closing of RBI/Kharchi Puja', '2017-07-01', 'BANK', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin',
        'admin');
INSERT INTO `FCHOLI` (`HOLIRFNUM`, `HOLINAME`, `HOLIDATE`, `HOLIMARKETSEGMENT`, `CREATEDATE`, `MODIFYDATE`, `CREATEDBY`, `LASTMODIFIEDBY`)
VALUES (29, 'Independence Day', '2017-08-15', 'BANK', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');
INSERT INTO `FCHOLI` (`HOLIRFNUM`, `HOLINAME`, `HOLIDATE`, `HOLIMARKETSEGMENT`, `CREATEDATE`, `MODIFYDATE`, `CREATEDBY`, `LASTMODIFIEDBY`)
VALUES (30, 'Independence Day', '2017-08-15', 'DEBT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');
INSERT INTO `FCHOLI` (`HOLIRFNUM`, `HOLINAME`, `HOLIDATE`, `HOLIMARKETSEGMENT`, `CREATEDATE`, `MODIFYDATE`, `CREATEDBY`, `LASTMODIFIEDBY`)
VALUES (31, 'Independence Day', '2017-08-15', 'EQUITY', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');
INSERT INTO `FCHOLI` (`HOLIRFNUM`, `HOLINAME`, `HOLIDATE`, `HOLIMARKETSEGMENT`, `CREATEDATE`, `MODIFYDATE`, `CREATEDBY`, `LASTMODIFIEDBY`)
VALUES (32, 'Parsi New Year', '2017-08-17', 'BANK', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');
INSERT INTO `FCHOLI` (`HOLIRFNUM`, `HOLINAME`, `HOLIDATE`, `HOLIMARKETSEGMENT`, `CREATEDATE`, `MODIFYDATE`, `CREATEDBY`, `LASTMODIFIEDBY`)
VALUES (33, 'Parsi New Year', '2017-08-17', 'DEBT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');
INSERT INTO `FCHOLI` (`HOLIRFNUM`, `HOLINAME`, `HOLIDATE`, `HOLIMARKETSEGMENT`, `CREATEDATE`, `MODIFYDATE`, `CREATEDBY`, `LASTMODIFIEDBY`)
VALUES (34, 'Ganesh Chaturthi', '2017-08-25', 'BANK', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');
INSERT INTO `FCHOLI` (`HOLIRFNUM`, `HOLINAME`, `HOLIDATE`, `HOLIMARKETSEGMENT`, `CREATEDATE`, `MODIFYDATE`, `CREATEDBY`, `LASTMODIFIEDBY`)
VALUES (35, 'Ganesh Chaturthi', '2017-08-25', 'DEBT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');
INSERT INTO `FCHOLI` (`HOLIRFNUM`, `HOLINAME`, `HOLIDATE`, `HOLIMARKETSEGMENT`, `CREATEDATE`, `MODIFYDATE`, `CREATEDBY`, `LASTMODIFIEDBY`)
VALUES (36, 'Ganesh Chaturthi', '2017-08-25', 'EQUITY', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');
INSERT INTO `FCHOLI` (`HOLIRFNUM`, `HOLINAME`, `HOLIDATE`, `HOLIMARKETSEGMENT`, `CREATEDATE`, `MODIFYDATE`, `CREATEDBY`, `LASTMODIFIEDBY`)
VALUES (37, 'Bakri Id (Id-ul-Zuha)/Karma Puja', '2017-09-02', 'BANK', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin',
        'admin');
INSERT INTO `FCHOLI` (`HOLIRFNUM`, `HOLINAME`, `HOLIDATE`, `HOLIMARKETSEGMENT`, `CREATEDATE`, `MODIFYDATE`, `CREATEDBY`, `LASTMODIFIEDBY`)
VALUES (38, 'Durga Puja/Dussehra (Vijaya Dashmi)', '2017-09-30', 'BANK', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin',
        'admin');
INSERT INTO `FCHOLI` (`HOLIRFNUM`, `HOLINAME`, `HOLIDATE`, `HOLIMARKETSEGMENT`, `CREATEDATE`, `MODIFYDATE`, `CREATEDBY`, `LASTMODIFIEDBY`)
VALUES (39, 'Mahatma Gandhi Jayanti', '2017-10-02', 'BANK', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');
INSERT INTO `FCHOLI` (`HOLIRFNUM`, `HOLINAME`, `HOLIDATE`, `HOLIMARKETSEGMENT`, `CREATEDATE`, `MODIFYDATE`, `CREATEDBY`, `LASTMODIFIEDBY`)
VALUES (40, 'Mahatma Gandhi Jayanti', '2017-10-02', 'DEBT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');
INSERT INTO `FCHOLI` (`HOLIRFNUM`, `HOLINAME`, `HOLIDATE`, `HOLIMARKETSEGMENT`, `CREATEDATE`, `MODIFYDATE`, `CREATEDBY`, `LASTMODIFIEDBY`)
VALUES (41, 'Mahatma Gandhi Jayanti', '2017-10-02', 'EQUITY', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');
INSERT INTO `FCHOLI` (`HOLIRFNUM`, `HOLINAME`, `HOLIDATE`, `HOLIMARKETSEGMENT`, `CREATEDATE`, `MODIFYDATE`, `CREATEDBY`, `LASTMODIFIEDBY`)
VALUES (42, 'Diwali * Laxmi Pujan', '2017-10-19', 'BANK', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');
INSERT INTO `FCHOLI` (`HOLIRFNUM`, `HOLINAME`, `HOLIDATE`, `HOLIMARKETSEGMENT`, `CREATEDATE`, `MODIFYDATE`, `CREATEDBY`, `LASTMODIFIEDBY`)
VALUES (43, 'Diwali * Laxmi Pujan', '2017-10-19', 'DEBT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');
INSERT INTO `FCHOLI` (`HOLIRFNUM`, `HOLINAME`, `HOLIDATE`, `HOLIMARKETSEGMENT`, `CREATEDATE`, `MODIFYDATE`, `CREATEDBY`, `LASTMODIFIEDBY`)
VALUES (44, 'Diwali * Laxmi Pujan', '2017-10-19', 'EQUITY', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');
INSERT INTO `FCHOLI` (`HOLIRFNUM`, `HOLINAME`, `HOLIDATE`, `HOLIMARKETSEGMENT`, `CREATEDATE`, `MODIFYDATE`, `CREATEDBY`, `LASTMODIFIEDBY`)
VALUES (45, 'Diwali Balipratipada', '2017-10-20', 'BANK', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');
INSERT INTO `FCHOLI` (`HOLIRFNUM`, `HOLINAME`, `HOLIDATE`, `HOLIMARKETSEGMENT`, `CREATEDATE`, `MODIFYDATE`, `CREATEDBY`, `LASTMODIFIEDBY`)
VALUES (46, 'Diwali Balipratipada', '2017-10-20', 'DEBT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');
INSERT INTO `FCHOLI` (`HOLIRFNUM`, `HOLINAME`, `HOLIDATE`, `HOLIMARKETSEGMENT`, `CREATEDATE`, `MODIFYDATE`, `CREATEDBY`, `LASTMODIFIEDBY`)
VALUES (47, 'Diwali Balipratipada', '2017-10-20', 'EQUITY', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');
INSERT INTO `FCHOLI` (`HOLIRFNUM`, `HOLINAME`, `HOLIDATE`, `HOLIMARKETSEGMENT`, `CREATEDATE`, `MODIFYDATE`, `CREATEDBY`, `LASTMODIFIEDBY`)
VALUES (48, 'Guru Nanak Jayanti/Kartika Purnima', '2017-11-04', 'BANK', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin',
        'admin');
INSERT INTO `FCHOLI` (`HOLIRFNUM`, `HOLINAME`, `HOLIDATE`, `HOLIMARKETSEGMENT`, `CREATEDATE`, `MODIFYDATE`, `CREATEDBY`, `LASTMODIFIEDBY`)
VALUES (49, 'Id-e-Milad', '2017-12-01', 'BANK', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');
INSERT INTO `FCHOLI` (`HOLIRFNUM`, `HOLINAME`, `HOLIDATE`, `HOLIMARKETSEGMENT`, `CREATEDATE`, `MODIFYDATE`, `CREATEDBY`, `LASTMODIFIEDBY`)
VALUES (50, 'Id-e-Milad', '2017-12-01', 'DEBT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');
INSERT INTO `FCHOLI` (`HOLIRFNUM`, `HOLINAME`, `HOLIDATE`, `HOLIMARKETSEGMENT`, `CREATEDATE`, `MODIFYDATE`, `CREATEDBY`, `LASTMODIFIEDBY`)
VALUES (51, 'Christmas', '2017-12-25', 'BANK', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');
INSERT INTO `FCHOLI` (`HOLIRFNUM`, `HOLINAME`, `HOLIDATE`, `HOLIMARKETSEGMENT`, `CREATEDATE`, `MODIFYDATE`, `CREATEDBY`, `LASTMODIFIEDBY`)
VALUES (52, 'Christmas', '2017-12-25', 'DEBT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');
INSERT INTO `FCHOLI` (`HOLIRFNUM`, `HOLINAME`, `HOLIDATE`, `HOLIMARKETSEGMENT`, `CREATEDATE`, `MODIFYDATE`, `CREATEDBY`, `LASTMODIFIEDBY`)
VALUES (53, 'Christmas', '2017-12-25', 'EQUITY', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');

SET FOREIGN_KEY_CHECKS = 0;

/* Drop Tables */

DROP TABLE IF EXISTS `FCSTTL` CASCADE;

/* Create Tables */

CREATE TABLE `FCSTTL`
(
  `STTLRFNUM`            BIGINT      NOT NULL AUTO_INCREMENT,
  `STTLEXTERNALID1`      VARCHAR(32) NULL,
  `STTLEXTERNALID2`      VARCHAR(32) NULL,
  `STTLSETTLEMENTTYPE`   CHAR(10)    NOT NULL
  COMMENT 'MF/Security',
  `STTLPAYINDATE`        DATE        NOT NULL,
  `STTLPAYOUTDATE`       DATE        NOT NULL,
  `STTLSECURITYPAYIN`    DATE        NOT NULL,
  `STTLSECURITYPAYOUT`   DATE        NOT NULL,
  `STTLTRADEDATE`        DATE        NOT NULL
  COMMENT 'Order Date',
  `STTLSETTLEMENTENTITY` VARCHAR(16) NOT NULL
  COMMENT 'BSE/AMC etc',
  `CREATEDATE`           TIMESTAMP   NOT NULL DEFAULT '2017-01-01 00:00:01',
  `MODIFYDATE`           TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATEDBY`            CHAR(64)    NOT NULL,
  `LASTMODIFIEDBY`       CHAR(64)    NOT NULL,
  CONSTRAINT `PK_FCSTTL` PRIMARY KEY (`STTLRFNUM` ASC)
)
  COMMENT = 'FCSTTL: Settlement Table';

SET FOREIGN_KEY_CHECKS = 1;

/* Added by sumit on 19042017  modified folio related tables.*/

DROP TABLE FCSLT;
DROP TABLE FCCBT;

SET FOREIGN_KEY_CHECKS = 0;

/* Drop Tables */

DROP TABLE IF EXISTS `FCASBT` CASCADE;

DROP TABLE IF EXISTS `FCASST` CASCADE;

DROP TABLE IF EXISTS `FCCOMT` CASCADE;

DROP TABLE IF EXISTS `FCCOST` CASCADE;

DROP TABLE IF EXISTS `FCCST` CASCADE;

DROP TABLE IF EXISTS `FCFHS` CASCADE;

DROP TABLE IF EXISTS `FCFHT` CASCADE;

DROP TABLE IF EXISTS `FCFOMT` CASCADE;

DROP TABLE IF EXISTS `FCFPT` CASCADE;

DROP TABLE IF EXISTS `FCSIP` CASCADE;

DROP TABLE IF EXISTS `FCSIPS` CASCADE;

DROP TABLE IF EXISTS `FCSLMT` CASCADE;

DROP TABLE IF EXISTS `FCSST` CASCADE;

DROP TABLE IF EXISTS `FCUFT` CASCADE;

/* Create Tables */

CREATE TABLE `FCASBT`
(
  `ASBTRFNUM`           BIGINT      NOT NULL AUTO_INCREMENT
  COMMENT 'Primary Key',
  `ASBTACCTNO`          VARCHAR(16) NULL
  COMMENT 'Account No (Fincash''s)',
  `ASBTBALANCETOBEPAID` DOUBLE      NULL
  COMMENT 'Balance to be Paid',
  `ASBTAMCTRFNUM`       BIGINT      NULL
  COMMENT 'Foreign Key to AMC Table (FCAMCT)',
  `CREATEDATE`          TIMESTAMP   NOT NULL DEFAULT '2017-01-01 00:00:01',
  `MODIFYDATE`          TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATEDBY`           CHAR(64)    NOT NULL,
  `LASTMODIFIEDBY`      CHAR(64)    NOT NULL,
  CONSTRAINT `PK_FCASBT` PRIMARY KEY (`ASBTRFNUM` ASC)
)
  COMMENT = 'FCASBT: AMC Scheme Balance Table';

CREATE TABLE `FCASST`
(
  `ASSTRFNUM`      BIGINT    NOT NULL AUTO_INCREMENT
  COMMENT 'Primary Key',
  `ASSTAMCTRFNUM`  BIGINT    NULL
  COMMENT 'Foreign Key to AMC Table (FCAMCT)',
  `ASSTSMTRFNUM`   BIGINT    NULL
  COMMENT 'Foreign Key to Scheme Master Table (FCSMT)',
  `ASSTASBTRFNUM`  BIGINT    NOT NULL,
  `ASSTAMOUNT`     DOUBLE    NOT NULL
  COMMENT 'Confirm Balance Amount',
  `ASSTISCREDIT`   CHAR(2)   NOT NULL
  COMMENT 'Y/N',
  `ASSTCOSTRFNUM`  BIGINT    NULL,
  `CREATEDATE`     TIMESTAMP NOT NULL DEFAULT '2017-01-01 00:00:01',
  `MODIFYDATE`     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATEDBY`      CHAR(64)  NOT NULL,
  `LASTMODIFIEDBY` CHAR(64)  NOT NULL,
  CONSTRAINT `PK_FCASST` PRIMARY KEY (`ASSTRFNUM` ASC)
)
  COMMENT = 'FCASST: AMC scheme Statement Table';

CREATE TABLE `FCCOMT`
(
  `COMTRFNUM`        BIGINT       NOT NULL AUTO_INCREMENT
  COMMENT 'Primary Key',
  `COMTCOMNAME`      VARCHAR(256) NOT NULL
  COMMENT 'Commission Name i.e. ICICI Upfront Commission',
  `COMTFROMDATE`     DATE         NOT NULL,
  `COMTTODATE`       DATE         NOT NULL,
  `COMTCOMACTIVE`    CHAR(2)      NOT NULL
  COMMENT 'Active: Y/N',
  `COMTCOMDESCPTION` VARCHAR(256) NULL
  COMMENT 'Commission Description',
  `COMTAMCTRFNUM`    BIGINT       NOT NULL
  COMMENT 'Foreign Key to AMC Table (AMCT)',
  `COMTSMTRFNUM`     BIGINT       NULL
  COMMENT 'Foreign Key to Scheme Master Table (SMT)',
  `COMTCTMTRFNUM`    BIGINT       NULL
  COMMENT 'Foreign Key to Category Master Table (CTMT)',
  `CREATEDATE`       TIMESTAMP    NOT NULL DEFAULT '2017-01-01 00:00:01',
  `MODIFYDATE`       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATEDBY`        CHAR(64)     NOT NULL,
  `LASTMODIFIEDBY`   CHAR(64)     NOT NULL,
  CONSTRAINT `PK_FCCOMT` PRIMARY KEY (`COMTRFNUM` ASC)
)
  COMMENT = 'FCCOMT: Commission Master Table';

CREATE TABLE `FCCOST`
(
  `COSTRFNUM`      BIGINT    NOT NULL AUTO_INCREMENT
  COMMENT 'Primary Key',
  `COSTAMCTRFNUM`  BIGINT    NULL
  COMMENT 'Foreign Key to AMC Table (AMCT)',
  `COSTSMTRFNUM`   BIGINT    NULL
  COMMENT 'Foreign Key to Scheme Master Table (SMT)',
  `COSTPLANTYPE`   CHAR(2)   NULL
  COMMENT 'Plan Type: SIP/LumpSum',
  `COSTAMOUNT`     DOUBLE    NULL
  COMMENT 'Commission Amount ',
  `COSTCSTRFNUM`   BIGINT    NULL
  COMMENT 'Foreign Key to Commission Structure Table (CST)',
  `COSTCOMTRFNUM`  BIGINT    NULL
  COMMENT 'Foreign Key to Commission Master Table (FCCOMT)',
  `COSTUFTRFNUM`   BIGINT    NULL
  COMMENT 'Foreign Key to User Folio Table (FCUFT)',
  `CREATEDATE`     TIMESTAMP NOT NULL DEFAULT '2017-01-01 00:00:01',
  `MODIFYDATE`     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATEDBY`      CHAR(64)  NOT NULL,
  `LASTMODIFIEDBY` CHAR(64)  NOT NULL,
  CONSTRAINT `PK_FCCOST` PRIMARY KEY (`COSTRFNUM` ASC)
)
  COMMENT = 'FCCOST: Commission Statement Table';

CREATE TABLE `FCCST`
(
  `CSTRFNUM`              BIGINT    NOT NULL AUTO_INCREMENT
  COMMENT 'Primary Key',
  `CSTCOMTYPE`            CHAR(3)   NOT NULL
  COMMENT 'Commission Type  Upfront (UP) Trailing (TR1) Onward Trail (TR2/TR3/TR4..) Additional Upfront (AU) Incentive (I) Additional Incentive (AI)',
  `CSTCOMTRFNUM`          BIGINT    NULL
  COMMENT 'Foreign Key to Commission Master Table',
  `CSTSLMTRFNUM`          BIGINT    NULL,
  `CSTLOCATION`           CHAR(4)   NOT NULL
  COMMENT 'T15/B15',
  `CSTCOMRATE`            FLOAT     NOT NULL
  COMMENT 'Commission Rate',
  `CSTISCOMPERCENTAGE`    CHAR(2)   NOT NULL
  COMMENT 'Is commission Percentage: Y/N',
  `CSTCLAWBACKPERIOD`     INT       NULL,
  `CSTCLAWBACKPERIODUNIT` CHAR(8)   NULL
  COMMENT 'Clawback Period Unit:  Daily (D) Weekly (W) Fortnightly (F) Monthly (M) Quarterly (Q) HalfYearly (H) Yearly (Y)',
  `CSTCALCPERIOD`         CHAR(2)   NULL
  COMMENT 'Calculation Period  Daily (D) Weekly (W) Fortnightly (F) Monthly (M) Quarterly (Q) HalfYearly (H) Yearly (Y)',
  `CSTISCLAWBACK`         CHAR(2)   NULL
  COMMENT 'Is Clawback Applicable: Y/N',
  `CSTCTMTRFNUM`          BIGINT    NULL
  COMMENT 'Not necessary',
  `CSTPLANTYPE`           CHAR(3)   NULL
  COMMENT 'Plan TYpe:  NFO (N) SIP (S) LumpSum (L) SwitchIn (SI) STP ',
  `CREATEDATE`            TIMESTAMP NOT NULL DEFAULT '2017-01-01 00:00:01',
  `MODIFYDATE`            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATEDBY`             CHAR(64)  NOT NULL,
  `LASTMODIFIEDBY`        CHAR(64)  NOT NULL,
  CONSTRAINT `PK_FCCST` PRIMARY KEY (`CSTRFNUM` ASC)
)
  COMMENT = 'FCCST: Commission Structure Table';

CREATE TABLE `FCFHS`
(
  `FHSRFNUM`           BIGINT       NOT NULL AUTO_INCREMENT
  COMMENT 'Primary Key',
  `FHSTYPE`            CHAR(2)      NULL
  COMMENT 'D: Debit C: Credit',
  `FHSUNITS`           DOUBLE       NULL
  COMMENT 'Quantity of the Order.',
  `FHSRTAREFNUM`       VARCHAR(32)  NULL
  COMMENT 'Order Id (For future usage)',
  `FHSSOTRFNUM`        BIGINT       NULL,
  `FHSSOPTRFNUM`       BIGINT       NOT NULL,
  `FHSNAV`             FLOAT        NOT NULL,
  `FHSAMOUNT`          DOUBLE       NOT NULL,
  `FHSDESCRIPTION`     VARCHAR(128) NULL
  COMMENT 'Transaction Description:  1. Purchase 2. Redemption 3. Dividend Reinvestment 4. Transfer-in',
  `FHSPOSTDATE`        DATE         NOT NULL,
  `FHSRTAREPORTDATE`   DATE         NOT NULL,
  `FHSTRANSACTIONMODE` CHAR(2)      NOT NULL
  COMMENT 'N: Normal R: Reversal TO: Transfer out TI: Transfer in',
  `FHSTRANSACTIONTYPE` CHAR(8)      NOT NULL
  COMMENT 'DR: Dividend Reinvestment P: Purchase R: Redemption SO: Switch out SI: Switch in etc',
  `FHSFHTRFNUM`        BIGINT       NOT NULL,
  `FHSRTASEQUENCENO`   VARCHAR(32)  NOT NULL,
  `FHSSTT`             DOUBLE       NOT NULL,
  `CREATEDATE`         TIMESTAMP    NOT NULL DEFAULT '2017-01-01 00:00:01',
  `MODIFYDATE`         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATEDBY`          CHAR(64)     NOT NULL,
  `LASTMODIFIEDBY`     CHAR(64)     NOT NULL,
  CONSTRAINT `PK_FCFHS` PRIMARY KEY (`FHSRFNUM` ASC)
)
  COMMENT = 'FCFHS: Folio Holding Statement';

CREATE TABLE `FCFHT`
(
  `FHTRFNUM`          BIGINT        NOT NULL AUTO_INCREMENT
  COMMENT 'Primary Key',
  `FHTHOLDINGNAME`    VARCHAR(128)  NULL
  COMMENT 'Name of the funds in the given Holding. (Multiple Rows in the table for multiple funds)',
  `FHTHOLDINGUNITS`   FLOAT         NULL
  COMMENT 'Units in individual Holding',
  `FHTTRADEDATE`      DATE          NULL
  COMMENT 'Purchase Date of the Holding.',
  `FHTCOMSTRUCTJSON`  VARCHAR(1024) NULL
  COMMENT 'JSON Object Creation',
  `FHTSOPTRFNUM`      BIGINT        NOT NULL,
  `FHTINVESTMENTMODE` CHAR(2)       NULL
  COMMENT 'SIP(S) /Lumpsum (L)',
  `FHTJSONNAME`       CHAR(32)      NULL,
  `FHTFOMTRFNUM`      BIGINT        NOT NULL,
  `FHTSOTRFNUM`       BIGINT        NULL,
  `FHTEXITLOAD`       VARCHAR(264)  NULL,
  `FHTSTATUS`         VARCHAR(32)   NOT NULL
  COMMENT 'Current Status: Fresh Allocation Partially Sold Completely Sold',
  `CREATEDATE`        TIMESTAMP     NOT NULL DEFAULT '2017-01-01 00:00:01',
  `MODIFYDATE`        TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATEDBY`         CHAR(64)      NOT NULL,
  `LASTMODIFIEDBY`    CHAR(64)      NOT NULL,
  CONSTRAINT `PK_Table1` PRIMARY KEY (`FHTRFNUM` ASC)
)
  COMMENT = 'FCFHT: Folio Holding Table';

CREATE TABLE `FCFOMT`
(
  `FOMTRFNUM`         BIGINT       NOT NULL AUTO_INCREMENT
  COMMENT 'Primary Key',
  `FOMTFOLIONAME`     VARCHAR(64)  NULL
  COMMENT 'Folio Name',
  `FOMTFOLIONO`       VARCHAR(32)  NOT NULL
  COMMENT 'Folio Number',
  `FOMTFOLIODESCP`    VARCHAR(128) NULL
  COMMENT 'Folio Description',
  `FOMTCREATIONDATE`  VARCHAR(50)  NULL
  COMMENT 'Folio Creation Date',
  `FOMTAMCNAME`       VARCHAR(256) NULL,
  `FOMTAMCTRFNUM`     BIGINT       NOT NULL,
  `FOMTOMTRFNUM`      BIGINT       NULL,
  `FOMTMODEOFHOLDING` CHAR(4)      NOT NULL
  COMMENT 'SI: Single JO: JOint AS: Anyone or Survivor',
  `FOMTSOTRFNUM`      BIGINT       NULL
  COMMENT 'Foreign Key to SubOrder Table (FCSOT)',
  `FOMTINVLOCTION`    CHAR(2)      NOT NULL
  COMMENT 'T for top-15 B for beyond-15',
  `FOMTJOINTPAN1`     CHAR(10)     NULL,
  `FOMTJOINTPAN2`     CHAR(10)     NULL,
  `CREATEDATE`        TIMESTAMP    NOT NULL DEFAULT '2017-01-01 00:00:01',
  `MODIFYDATE`        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATEDBY`         CHAR(64)     NOT NULL,
  `LASTMODIFIEDBY`    CHAR(64)     NOT NULL,
  CONSTRAINT `PK_FCFOMT` PRIMARY KEY (`FOMTRFNUM` ASC)
)
  COMMENT = 'FCFOMT: Folio Master Table';

CREATE TABLE `FCFPT`
(
  `FPTRFNUM`           BIGINT      NOT NULL AUTO_INCREMENT,
  `FPTFOMTRFNUM`       BIGINT      NOT NULL,
  `FPTEXTERNALID`      VARCHAR(32) NULL,
  `FPTAMOUNT`          DOUBLE      NOT NULL
  COMMENT 'Payout Amount',
  `FPTCREDITDATE`      DATE        NULL,
  `FPTDECLARATIONDATE` DATE        NULL,
  `FPTINVESTMENTMODE`  CHAR(2)     NULL,
  `FPTSOPTRFNUM`       BIGINT      NOT NULL,
  `FPTPAYOUTTYPE`      CHAR(2)     NULL
  COMMENT 'Dividend / Special Dividend (Dividend Type)',
  `CREATEDATE`         TIMESTAMP   NOT NULL DEFAULT '2017-01-01 00:00:01',
  `MODIFYDATE`         TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATEDBY`          CHAR(64)    NOT NULL,
  `LASTMODIFIEDBY`     CHAR(64)    NOT NULL,
  CONSTRAINT `PK_FCFPT` PRIMARY KEY (`FPTRFNUM` ASC)
)
  COMMENT = 'FCFPT: Folio Payout Table';

CREATE TABLE `FCSIP`
(
  `SIPRFNUM`             BIGINT      NOT NULL AUTO_INCREMENT,
  `SIPSTARTDATE`         TIMESTAMP   NOT NULL DEFAULT '2017-01-01 00:00:01',
  `SIPENDDATE`           TIMESTAMP   NULL,
  `SIPINSTALLMENTAMOUNT` DOUBLE      NOT NULL,
  `SIPFREQUENCY`         CHAR(2)     NOT NULL
  COMMENT 'Weekly (w) Monthly (M) Quarterly (Q) Half-Yearly (H) Yearly (Y)',
  `SIPNOOFINSTALLMENTS`  INT         NOT NULL,
  `SIPSTATUS`            CHAR(16)    NOT NULL
  COMMENT 'Canceled Active',
  `SIPEXTERNALID`        VARCHAR(16) NULL,
  `SIPDEDUCTIONDAY`      INT         NOT NULL,
  `SIPSOTRFNUM`          BIGINT      NOT NULL,
  `SIPFOMTRFNUM`         BIGINT      NOT NULL,
  `CREATEDATE`           TIMESTAMP   NOT NULL DEFAULT '2017-01-01 00:00:01',
  `MODIFYDATE`           TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATEDBY`            CHAR(64)    NOT NULL,
  `LASTMODIFIEDBY`       CHAR(64)    NOT NULL,
  CONSTRAINT `PK_FCSIP` PRIMARY KEY (`SIPRFNUM` ASC)
)
  COMMENT = 'FCSIP: SIP Table';

CREATE TABLE `FCSIPS`
(
  `SIPSRFNUM`      BIGINT    NOT NULL AUTO_INCREMENT,
  `SIPSSCHEDULE`   DATE      NOT NULL,
  `SIPAMOUNT`      DOUBLE    NULL,
  `SIPSSIPRFNUM`   BIGINT    NOT NULL,
  `CREATEDATE`     TIMESTAMP NOT NULL DEFAULT '2017-01-01 00:00:01',
  `MODIFYDATE`     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATEDBY`      CHAR(64)  NOT NULL,
  `LASTMODIFIEDBY` CHAR(64)  NOT NULL,
  CONSTRAINT `PK_FCSIPS` PRIMARY KEY (`SIPSRFNUM` ASC)
)
  COMMENT = 'FCSIPS: SIP Schedule';

CREATE TABLE `FCSLMT`
(
  `SLMTRFNUM`      BIGINT       NOT NULL AUTO_INCREMENT
  COMMENT 'Primary Key',
  `SLMTFROM`       DOUBLE       NULL
  COMMENT 'Slab Start From',
  `SLMTTO`         DOUBLE       NULL
  COMMENT 'Slab goes to',
  `SLMTSLABNAME`   VARCHAR(64)  NULL
  COMMENT 'Slab Name',
  `SLMTSLABTYPE`   CHAR(8)      NOT NULL
  COMMENT 'Type of Slab',
  `SLMTSLABACTIVE` CHAR(2)      NULL
  COMMENT 'Slab Active: Y/N',
  `SLMTDESCPTION`  VARCHAR(256) NULL
  COMMENT 'Slab Description',
  `SLMTCOMTRFNUM`  BIGINT       NULL
  COMMENT 'Foreign Key to Commission Master Table (COMT)',
  `CREATEDATE`     TIMESTAMP    NOT NULL DEFAULT '2017-01-01 00:00:01',
  `MODIFYDATE`     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATEDBY`      CHAR(64)     NOT NULL,
  `LASTMODIFIEDBY` CHAR(10)     NOT NULL,
  CONSTRAINT `PK_FCSLMT` PRIMARY KEY (`SLMTRFNUM` ASC)
)
  COMMENT = 'FCSLMT: Slab Master Table';

CREATE TABLE `FCSST`
(
  `SSTRFNUM`        BIGINT    NOT NULL AUTO_INCREMENT,
  `SSTSIPRFNUM`     BIGINT    NOT NULL,
  `SSTCREDITAMOUNT` DOUBLE    NOT NULL,
  `SSTCREDITDATE`   DATE      NOT NULL,
  `CREATEDATE`      TIMESTAMP NOT NULL DEFAULT '2017-01-01 00:00:01',
  `MODIFYDATE`      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATEDBY`       CHAR(64)  NOT NULL,
  `LASTMODIFIEDBY`  CHAR(64)  NOT NULL,
  CONSTRAINT `PK_FCSST` PRIMARY KEY (`SSTRFNUM` ASC)
)
  COMMENT = 'FCSST: SIP STATEMENT TABLE';

CREATE TABLE `FCUFT`
(
  `UFTRFNUM`       BIGINT    NOT NULL AUTO_INCREMENT
  COMMENT 'Primary Key',
  `UFTFOMTRFNUM`   BIGINT    NULL
  COMMENT 'Foreign Key to Folio Master Table (FCFOMT)',
  `UFTUBDRFNUM`    BIGINT    NOT NULL
  COMMENT 'Foreign Key to User Basic Details Table (FCUBD)',
  `CREATEDATE`     TIMESTAMP NOT NULL DEFAULT '2017-01-01 00:00:01',
  `MODIFYDATE`     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATEDBY`      CHAR(64)  NOT NULL,
  `LASTMODIFIEDBY` CHAR(64)  NOT NULL,
  `UFTSOTRFNUM`    BIGINT    NULL,
  CONSTRAINT `PK_FCUFT` PRIMARY KEY (`UFTRFNUM` ASC)
)
  COMMENT = 'FCUFT: User Folio Table';

/* Create Foreign Key Constraints */

ALTER TABLE `FCASBT`
  ADD CONSTRAINT `FK_FCASBT_FCAMCT`
FOREIGN KEY (`ASBTAMCTRFNUM`) REFERENCES `FCAMCT` (`AMCTRFNUM`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `FCASST`
  ADD CONSTRAINT `FK_FCASST_FCAMCT`
FOREIGN KEY (`ASSTAMCTRFNUM`) REFERENCES `FCAMCT` (`AMCTRFNUM`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `FCASST`
  ADD CONSTRAINT `FK_FCASST_FCASBT`
FOREIGN KEY (`ASSTASBTRFNUM`) REFERENCES `FCASBT` (`ASBTRFNUM`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `FCASST`
  ADD CONSTRAINT `FK_FCASST_FCCOST`
FOREIGN KEY (`ASSTCOSTRFNUM`) REFERENCES `FCCOST` (`COSTRFNUM`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `FCASST`
  ADD CONSTRAINT `FK_FCASST_FCSMT`
FOREIGN KEY (`ASSTSMTRFNUM`) REFERENCES `FCSMT` (`SMTRFNUM`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `FCCOMT`
  ADD CONSTRAINT `FK_FCCOMT_FCAMCT`
FOREIGN KEY (`COMTAMCTRFNUM`) REFERENCES `FCAMCT` (`AMCTRFNUM`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `FCCOMT`
  ADD CONSTRAINT `FK_FCCOMT_FCCTMT`
FOREIGN KEY (`COMTCTMTRFNUM`) REFERENCES `FCCTMT` (`CTMTRFNUM`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `FCCOMT`
  ADD CONSTRAINT `FK_FCCOMT_FCSMT`
FOREIGN KEY (`COMTSMTRFNUM`) REFERENCES `FCSMT` (`SMTRFNUM`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `FCCOST`
  ADD CONSTRAINT `FK_FCCOST_FCAMCT`
FOREIGN KEY (`COSTAMCTRFNUM`) REFERENCES `FCAMCT` (`AMCTRFNUM`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `FCCOST`
  ADD CONSTRAINT `FK_FCCOST_FCCOMT`
FOREIGN KEY (`COSTCOMTRFNUM`) REFERENCES `FCCOMT` (`COMTRFNUM`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `FCCOST`
  ADD CONSTRAINT `FK_FCCOST_FCCST`
FOREIGN KEY (`COSTCSTRFNUM`) REFERENCES `FCCST` (`CSTRFNUM`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `FCCOST`
  ADD CONSTRAINT `FK_FCCOST_FCSMT`
FOREIGN KEY (`COSTSMTRFNUM`) REFERENCES `FCSMT` (`SMTRFNUM`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `FCCOST`
  ADD CONSTRAINT `FK_FCCOST_FCUFT`
FOREIGN KEY (`COSTUFTRFNUM`) REFERENCES `FCUFT` (`UFTRFNUM`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `FCCST`
  ADD CONSTRAINT `FK_FCCST_FCCOMT`
FOREIGN KEY (`CSTCOMTRFNUM`) REFERENCES `FCCOMT` (`COMTRFNUM`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `FCCST`
  ADD CONSTRAINT `FK_FCCST_FCCTMT`
FOREIGN KEY (`CSTCTMTRFNUM`) REFERENCES `FCCTMT` (`CTMTRFNUM`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `FCCST`
  ADD CONSTRAINT `FK_FCCST_FCSLMT`
FOREIGN KEY (`CSTSLMTRFNUM`) REFERENCES `FCSLMT` (`SLMTRFNUM`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `FCFHS`
  ADD CONSTRAINT `FK_FCFHS_FCFHT`
FOREIGN KEY (`FHSFHTRFNUM`) REFERENCES `FCFHT` (`FHTRFNUM`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `FCFHS`
  ADD CONSTRAINT `FK_FCFHS_FCSOPT`
FOREIGN KEY (`FHSSOPTRFNUM`) REFERENCES `FCSOPT` (`SOPTRFNUM`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `FCFHS`
  ADD CONSTRAINT `FK_FCFHS_FCSOT`
FOREIGN KEY (`FHSSOTRFNUM`) REFERENCES `FCSOT` (`SOTRFNUM`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `FCFHT`
  ADD CONSTRAINT `FK_FCFHT_FCFOMT`
FOREIGN KEY (`FHTFOMTRFNUM`) REFERENCES `FCFOMT` (`FOMTRFNUM`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `FCFHT`
  ADD CONSTRAINT `FK_FCFHT_FCSOPT`
FOREIGN KEY (`FHTSOPTRFNUM`) REFERENCES `FCSOPT` (`SOPTRFNUM`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `FCFHT`
  ADD CONSTRAINT `FK_FCFHT_FCSOT`
FOREIGN KEY (`FHTSOTRFNUM`) REFERENCES `FCSOT` (`SOTRFNUM`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `FCFOMT`
  ADD CONSTRAINT `FK_FCFOMT_FCAMCT`
FOREIGN KEY (`FOMTAMCTRFNUM`) REFERENCES `FCAMCT` (`AMCTRFNUM`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `FCFOMT`
  ADD CONSTRAINT `FK_FCFOMT_FCOMT`
FOREIGN KEY (`FOMTOMTRFNUM`) REFERENCES `FCOMT` (`OMTRFNUM`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `FCFOMT`
  ADD CONSTRAINT `FK_FCFOMT_FCSOT`
FOREIGN KEY (`FOMTSOTRFNUM`) REFERENCES `FCSOT` (`SOTRFNUM`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `FCFPT`
  ADD CONSTRAINT `FK_FCFPT_FCFOMT`
FOREIGN KEY (`FPTFOMTRFNUM`) REFERENCES `FCFOMT` (`FOMTRFNUM`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `FCFPT`
  ADD CONSTRAINT `FK_FCFPT_FCSOPT`
FOREIGN KEY (`FPTSOPTRFNUM`) REFERENCES `FCSOPT` (`SOPTRFNUM`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `FCSIP`
  ADD CONSTRAINT `FK_FCSIP_FCFOMT`
FOREIGN KEY (`SIPFOMTRFNUM`) REFERENCES `FCFOMT` (`FOMTRFNUM`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `FCSIP`
  ADD CONSTRAINT `FK_FCSIP_FCSOT`
FOREIGN KEY (`SIPSOTRFNUM`) REFERENCES `FCSOT` (`SOTRFNUM`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `FCSIPS`
  ADD CONSTRAINT `FK_FCSIPS_FCSIP`
FOREIGN KEY (`SIPSSIPRFNUM`) REFERENCES `FCSIP` (`SIPRFNUM`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `FCSLMT`
  ADD CONSTRAINT `FK_FCSLMT_FCCOMT`
FOREIGN KEY (`SLMTCOMTRFNUM`) REFERENCES `FCCOMT` (`COMTRFNUM`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `FCSST`
  ADD CONSTRAINT `FK_FCSST_FCSIP`
FOREIGN KEY (`SSTSIPRFNUM`) REFERENCES `FCSIP` (`SIPRFNUM`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `FCUFT`
  ADD CONSTRAINT `FK_FCUFT_FCFOMT`
FOREIGN KEY (`UFTFOMTRFNUM`) REFERENCES `FCFOMT` (`FOMTRFNUM`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `FCUFT`
  ADD CONSTRAINT `FK_FCUFT_FCSOT`
FOREIGN KEY (`UFTSOTRFNUM`) REFERENCES `FCSOT` (`SOTRFNUM`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `FCUFT`
  ADD CONSTRAINT `FK_FCUFT_FCUBD`
FOREIGN KEY (`UFTUBDRFNUM`) REFERENCES `FCUBD` (`UBDRFNUM`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

SET FOREIGN_KEY_CHECKS = 1;


/* Added by sumit on 19042017  modified folio table column name tables.*/

ALTER TABLE FCFHS
  CHANGE FHSNAV FHSPRICE FLOAT NOT NULL;


/* Added by sumit on 19042017  modified folio related tables.*/

SET FOREIGN_KEY_CHECKS = 0;

/* Drop Tables */

DROP TABLE IF EXISTS `FCFHT` CASCADE;

DROP TABLE IF EXISTS `FCFOMT` CASCADE;

/* Create Tables */

CREATE TABLE `FCFHT`
(
  `FHTRFNUM`          BIGINT        NOT NULL AUTO_INCREMENT
  COMMENT 'Primary Key',
  `FHTHOLDINGNAME`    VARCHAR(128)  NULL
  COMMENT 'Name of the funds in the given Holding. (Multiple Rows in the table for multiple funds)',
  `FHTHOLDINGUNITS`   FLOAT         NULL
  COMMENT 'Units in individual Holding',
  `FHTTRADEDATE`      DATE          NULL
  COMMENT 'Purchase Date of the Holding.',
  `FHTCOMSTRUCTJSON`  VARCHAR(1024) NULL
  COMMENT 'JSON Object Creation',
  `FHTSOPTRFNUM`      BIGINT        NOT NULL,
  `FHTINVESTMENTMODE` CHAR(2)       NULL
  COMMENT 'SIP(S) /Lumpsum (L)',
  `FHTJSONNAME`       CHAR(32)      NULL,
  `FHTFOMTRFNUM`      BIGINT        NOT NULL,
  `FHTSOTRFNUM`       BIGINT        NULL,
  `FHTEXITLOAD`       VARCHAR(264)  NULL,
  `FHTINVLOCATION`    CHAR(2)       NOT NULL
  COMMENT 'T: Top-15 B: Beyond 15',
  `FHTSTATUS`         VARCHAR(32)   NOT NULL
  COMMENT 'Current Status: Fresh Allocation Partially Sold Completely Sold',
  `CREATEDATE`        TIMESTAMP     NOT NULL DEFAULT '2017-01-01 00:00:01',
  `MODIFYDATE`        TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATEDBY`         CHAR(64)      NOT NULL,
  `LASTMODIFIEDBY`    CHAR(64)      NOT NULL,
  CONSTRAINT `PK_Table1` PRIMARY KEY (`FHTRFNUM` ASC)
)
  COMMENT = 'FCFHT: Folio Holding Table';

CREATE TABLE `FCFOMT`
(
  `FOMTRFNUM`         BIGINT       NOT NULL AUTO_INCREMENT
  COMMENT 'Primary Key',
  `FOMTFOLIONAME`     VARCHAR(64)  NULL
  COMMENT 'Folio Name',
  `FOMTFOLIONO`       VARCHAR(32)  NOT NULL
  COMMENT 'Folio Number',
  `FOMTFOLIODESCP`    VARCHAR(128) NULL
  COMMENT 'Folio Description',
  `FOMTCREATIONDATE`  VARCHAR(50)  NULL
  COMMENT 'Folio Creation Date',
  `FOMTAMCNAME`       VARCHAR(256) NULL,
  `FOMTAMCTRFNUM`     BIGINT       NOT NULL,
  `FOMTOMTRFNUM`      BIGINT       NULL,
  `FOMTMODEOFHOLDING` CHAR(4)      NOT NULL
  COMMENT 'SI: Single JO: JOint AS: Anyone or Survivor',
  `FOMTSOTRFNUM`      BIGINT       NULL
  COMMENT 'Foreign Key to SubOrder Table (FCSOT)',
  `FOMTJOINTPAN1`     CHAR(10)     NULL,
  `FOMTJOINTPAN2`     CHAR(10)     NULL,
  `CREATEDATE`        TIMESTAMP    NOT NULL DEFAULT '2017-01-01 00:00:01',
  `MODIFYDATE`        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATEDBY`         CHAR(64)     NOT NULL,
  `LASTMODIFIEDBY`    CHAR(64)     NOT NULL,
  CONSTRAINT `PK_FCFOMT` PRIMARY KEY (`FOMTRFNUM` ASC)
)
  COMMENT = 'FCFOMT: Folio Master Table';

/* Create Foreign Key Constraints */

ALTER TABLE `FCFHT`
  ADD CONSTRAINT `FK_FCFHT_FCFOMT`
FOREIGN KEY (`FHTFOMTRFNUM`) REFERENCES `FCFOMT` (`FOMTRFNUM`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `FCFHT`
  ADD CONSTRAINT `FK_FCFHT_FCSOPT`
FOREIGN KEY (`FHTSOPTRFNUM`) REFERENCES `FCSOPT` (`SOPTRFNUM`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `FCFHT`
  ADD CONSTRAINT `FK_FCFHT_FCSOT`
FOREIGN KEY (`FHTSOTRFNUM`) REFERENCES `FCSOT` (`SOTRFNUM`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `FCFOMT`
  ADD CONSTRAINT `FK_FCFOMT_FCAMCT`
FOREIGN KEY (`FOMTAMCTRFNUM`) REFERENCES `FCAMCT` (`AMCTRFNUM`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `FCFOMT`
  ADD CONSTRAINT `FK_FCFOMT_FCOMT`
FOREIGN KEY (`FOMTOMTRFNUM`) REFERENCES `FCOMT` (`OMTRFNUM`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `FCFOMT`
  ADD CONSTRAINT `FK_FCFOMT_FCSOT`
FOREIGN KEY (`FOMTSOTRFNUM`) REFERENCES `FCSOT` (`SOTRFNUM`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

SET FOREIGN_KEY_CHECKS = 1;


/* Added by sumit on 19042017  modified folio related tables.*/

SET FOREIGN_KEY_CHECKS = 0;

/* Drop Tables */

DROP TABLE IF EXISTS `FCFHS` CASCADE;

DROP TABLE IF EXISTS `FCFHT` CASCADE;

/* Create Tables */

CREATE TABLE `FCFHS`
(
  `FHSRFNUM`           BIGINT       NOT NULL AUTO_INCREMENT
  COMMENT 'Primary Key',
  `FHSTYPE`            CHAR(2)      NOT NULL
  COMMENT 'D: Debit C: Credit',
  `FHSUNITS`           DOUBLE       NOT NULL
  COMMENT 'Quantity of the Order.',
  `FHSRTAREFNUM`       VARCHAR(32)  NOT NULL
  COMMENT 'Order Id (For future usage)',
  `FHSSOTRFNUM`        BIGINT       NULL,
  `FHSSOPTRFNUM`       BIGINT       NOT NULL,
  `FHSPRICE`           DOUBLE       NOT NULL,
  `FHSAMOUNT`          DOUBLE       NOT NULL,
  `FHSDESCRIPTION`     VARCHAR(128) NULL
  COMMENT 'Transaction Description:  1. Purchase 2. Redemption 3. Dividend Reinvestment 4. Transfer-in',
  `FHSPOSTDATE`        DATE         NOT NULL,
  `FHSRTAREPORTDATE`   DATE         NOT NULL,
  `FHSTRANSACTIONMODE` CHAR(2)      NOT NULL
  COMMENT 'N: Normal R: Reversal TO: Transfer out TI: Transfer in',
  `FHSTRANSACTIONTYPE` CHAR(8)      NOT NULL
  COMMENT 'DR: Dividend Reinvestment P: Purchase R: Redemption SO: Switch out SI: Switch in etc',
  `FHSFHTRFNUM`        BIGINT       NOT NULL,
  `FHSRTASEQUENCENO`   VARCHAR(32)  NOT NULL,
  `FHSSTT`             DOUBLE       NOT NULL,
  `CREATEDATE`         TIMESTAMP    NOT NULL DEFAULT '2017-01-01 00:00:01',
  `MODIFYDATE`         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATEDBY`          CHAR(64)     NOT NULL,
  `LASTMODIFIEDBY`     CHAR(64)     NOT NULL,
  CONSTRAINT `PK_FCFHS` PRIMARY KEY (`FHSRFNUM` ASC)
)
  COMMENT = 'FCFHS: Folio Holding Statement';

CREATE TABLE `FCFHT`
(
  `FHTRFNUM`          BIGINT        NOT NULL AUTO_INCREMENT
  COMMENT 'Primary Key',
  `FHTHOLDINGNAME`    VARCHAR(128)  NULL
  COMMENT 'Name of the funds in the given Holding. (Multiple Rows in the table for multiple funds)',
  `FHTHOLDINGUNITS`   DOUBLE        NOT NULL
  COMMENT 'Units in individual Holding',
  `FHTTRADEDATE`      DATE          NOT NULL
  COMMENT 'Purchase Date of the Holding.',
  `FHTCOMSTRUCTJSON`  VARCHAR(2048) NULL
  COMMENT 'JSON Object Creation',
  `FHTSOPTRFNUM`      BIGINT        NOT NULL,
  `FHTINVESTMENTMODE` CHAR(2)       NOT NULL
  COMMENT 'SIP(S) /Lumpsum (L)',
  `FHTJSONNAME`       CHAR(32)      NULL,
  `FHTFOMTRFNUM`      BIGINT        NOT NULL,
  `FHTSOTRFNUM`       BIGINT        NULL,
  `FHTEXITLOAD`       VARCHAR(264)  NULL,
  `FHTINVLOCATION`    CHAR(2)       NOT NULL
  COMMENT 'T: Top-15 B: Beyond 15',
  `FHTSTATUS`         VARCHAR(32)   NOT NULL
  COMMENT 'Current Status: Fresh Allocation Partially Sold Completely Sold',
  `CREATEDATE`        TIMESTAMP     NOT NULL DEFAULT '2017-01-01 00:00:01',
  `MODIFYDATE`        TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATEDBY`         CHAR(64)      NOT NULL,
  `LASTMODIFIEDBY`    CHAR(64)      NOT NULL,
  CONSTRAINT `PK_Table1` PRIMARY KEY (`FHTRFNUM` ASC)
)
  COMMENT = 'FCFHT: Folio Holding Table';

/* Create Foreign Key Constraints */

ALTER TABLE `FCFHS`
  ADD CONSTRAINT `FK_FCFHS_FCFHT`
FOREIGN KEY (`FHSFHTRFNUM`) REFERENCES `FCFHT` (`FHTRFNUM`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `FCFHS`
  ADD CONSTRAINT `FK_FCFHS_FCSOPT`
FOREIGN KEY (`FHSSOPTRFNUM`) REFERENCES `FCSOPT` (`SOPTRFNUM`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `FCFHS`
  ADD CONSTRAINT `FK_FCFHS_FCSOT`
FOREIGN KEY (`FHSSOTRFNUM`) REFERENCES `FCSOT` (`SOTRFNUM`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `FCFHT`
  ADD CONSTRAINT `FK_FCFHT_FCFOMT`
FOREIGN KEY (`FHTFOMTRFNUM`) REFERENCES `FCFOMT` (`FOMTRFNUM`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `FCFHT`
  ADD CONSTRAINT `FK_FCFHT_FCSOPT`
FOREIGN KEY (`FHTSOPTRFNUM`) REFERENCES `FCSOPT` (`SOPTRFNUM`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `FCFHT`
  ADD CONSTRAINT `FK_FCFHT_FCSOT`
FOREIGN KEY (`FHTSOTRFNUM`) REFERENCES `FCSOT` (`SOTRFNUM`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

SET FOREIGN_KEY_CHECKS = 1;


SET FOREIGN_KEY_CHECKS = 0;

/* Drop Tables */

DROP TABLE IF EXISTS `FCSIA` CASCADE;

/* Create Tables */

CREATE TABLE `FCSIA`
(
  `SIARFNUM`       BIGINT      NOT NULL AUTO_INCREMENT,
  `SIASMTRFNUM`    BIGINT      NOT NULL,
  `SIAIMTRFNUM`    BIGINT      NOT NULL,
  `SIATXNTYPE`     CHAR(2)     NOT NULL
  COMMENT 'Buy(B)/Sell(S)',
  `SIAEXTFIELD`    VARCHAR(64) NULL,
  `CREATEDATE`     TIMESTAMP   NOT NULL DEFAULT '2017-01-01 00:00:01',
  `MODIFYDATE`     TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATEDBY`      CHAR(64)    NOT NULL,
  `LASTMODIFIEDBY` CHAR(64)    NOT NULL,
  CONSTRAINT `PK_FCSIA` PRIMARY KEY (`SIARFNUM` ASC)
)
  COMMENT = 'FCSIA: Scheme Integration Association';

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `FCSIA`
  ADD CONSTRAINT `UNQ_SMT_IMT_TXNTYPE` UNIQUE (`SIASMTRFNUM` ASC, `SIAIMTRFNUM` ASC, `SIATXNTYPE` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `FCSIA`
  ADD CONSTRAINT `FK_FCSIA_FCIMT`
FOREIGN KEY (`SIAIMTRFNUM`) REFERENCES `FCIMT` (`IMTRFNUM`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE `FCSIA`
  ADD CONSTRAINT `FK_FCSIA_FCSMT`
FOREIGN KEY (`SIASMTRFNUM`) REFERENCES `FCSMT` (`SMTRFNUM`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

SET FOREIGN_KEY_CHECKS = 1;

INSERT INTO FCIMT (IMTRFNUM,IMTINTGRATNAME, IMTINTGRATACTIVE, IMTINTGRATDESCRP, CREATEDATE, MODIFYDATE, CREATEDBY, LASTMODIFIEDBY)
VALUES (2,'RELIANCE', 'Y', 'Reliance', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');
INSERT INTO FCSIA (SIASMTRFNUM, SIAIMTRFNUM, SIATXNTYPE, CREATEDATE, MODIFYDATE, CREATEDBY, LASTMODIFIEDBY)
VALUES (3495, 2, 'R', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');

ALTER TABLE `FCKYC`
  ADD COLUMN `KYCIDVERIFICATION` CHAR(2) NOT NULL DEFAULT 'UP'
  AFTER `KYCDMTSIGNATURE`;
ALTER TABLE `FCKYC`
  MODIFY COLUMN `KYCIDVERIFICATION` CHAR(2) NOT NULL DEFAULT 'UP'
  COMMENT 'APPROVED 	A\nREJECTED	R\nUNDER PROCESS	UP';

ALTER TABLE `FCKYC`
  ADD COLUMN `KYCPHOTOVERIFICATION` CHAR(2) NOT NULL DEFAULT 'UP'
  AFTER `KYCIDVERIFICATION`;
ALTER TABLE `FCKYC`
  MODIFY COLUMN `KYCPHOTOVERIFICATION` CHAR(2) NOT NULL DEFAULT 'UP'
  COMMENT 'APPROVED 	A\nREJECTED	R\nUNDER PROCESS	UP';

ALTER TABLE `FCKYC`
  ADD COLUMN `KYCSIGNVERIFICATION` CHAR(2) NOT NULL DEFAULT 'UP'
  AFTER `KYCPHOTOVERIFICATION`;
ALTER TABLE `FCKYC`
  MODIFY COLUMN `KYCSIGNVERIFICATION` CHAR(2) NOT NULL DEFAULT 'UP'
  COMMENT 'APPROVED 	A\nREJECTED	R\nUNDER PROCESS	UP';

ALTER TABLE `FCUAA`
  ADD COLUMN `UAADOCSTATUS` CHAR(2) NOT NULL DEFAULT 'UP'
  AFTER `UAAREGION`;
ALTER TABLE `FCUAA`
  MODIFY COLUMN `UAADOCSTATUS` CHAR(2) NOT NULL DEFAULT 'UP'
  COMMENT 'APPROVED 	A\nREJECTED	R\nUNDER PROCESS	UP';


/* Added by sumit on 20-04-2017 for SOPTRTASCHEMECODE modification*/
UPDATE FCSOPT sopt, FCSMT smt
SET SOPTRTASCHEMECODE = CONCAT(sopt.SOPTRTACODE, sopt.SOPTOPTIONCODE)
WHERE SMTRTACODERFNUM = 2 AND smt.SMTRFNUM = sopt.SOPTSMTRFNUM;

/* ULT TABLE */
ALTER TABLE FCULT
  MODIFY ULTPASSWORD VARCHAR(128) NOT NULL;

/* Added by sumit on 20-04-2017 for FHS modification*/
ALTER TABLE FCFHS
  ADD FHSTRADEDATE DATE NOT NULL;

INSERT INTO FCOSTM (OSTMNAME, OSTMACTIVE, OSTMDESCRIP, OSTMDISPLAYNAME, CREATEDATE, MODIFYDATE, CREATEDBY, LASTMODIFIEDBY)
VALUES ('ORDER_FAILED', 'Y', 'Order failed', 'Order Failed', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM');

/* Added by sumit on 26-04-2017 for Order State Addition*/
INSERT INTO FCOSTM (OSTMNAME, OSTMACTIVE, OSTMDESCRIP, OSTMDISPLAYNAME, CREATEDATE, MODIFYDATE, CREATEDBY, LASTMODIFIEDBY)
VALUES
  ('ORDER_REVERSED', 'Y', 'Order Reversed', 'Order Reversed', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM');

ALTER TABLE FCSOT CHANGE COLUMN SOTSIPFREQUENCY SOTSIPFREQUENCY CHAR(2) NULL DEFAULT NULL COMMENT 'Monthly/HalfYearly' AFTER SOTUBDRFNUM,
  CHANGE COLUMN SOTSIPINSTALLMENTS SOTSIPINSTALLMENTS INT(11) NULL DEFAULT NULL COMMENT 'SIP No. of Installments' AFTER SOTSIPFREQUENCY;

INSERT INTO FCACT (ACTCONSTANTNAME, ACTCONSTANTVALUE, ACTACTIVE, CREATEDATE, MODIFYDATE, CREATEDBY, LASTMODIFIEDBY)
VALUES ('BSE_PAY_START_CUTOFF', '15:00:00', 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');

INSERT INTO FCACT (ACTCONSTANTNAME, ACTCONSTANTVALUE, ACTACTIVE, CREATEDATE, MODIFYDATE, CREATEDBY, LASTMODIFIEDBY)
VALUES ('BSE_PAY_CUTOFF', '09:00:00', 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');

/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 04-May-2017 13:40:06 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
;

/* Drop Tables */

DROP TABLE IF EXISTS `FCBSUF` CASCADE
;

/* Create Tables */

CREATE TABLE `FCBSUF`
(
  `BSUFRFNUM` BIGINT NOT NULL AUTO_INCREMENT,
  `BSUFEBSERFNUM` BIGINT NOT NULL,
  `BSUFSUFFIXCODE` VARCHAR(16) NOT NULL,
  `BSUFISTIMEBASED` CHAR(2) NOT NULL,
  `BSUFISAMOUNTBASED` CHAR(2) NOT NULL,
  `BSUFBSECUTOFFTIME` TIME 	 NULL,
  `BSUFTHRESOLDAMOUNT` DOUBLE 	 NULL,
  `BSUFPREFIXCODE` VARCHAR(16) 	 NULL,
  `BSUFSTPFLAG` VARCHAR(2) 	 NULL,
  `BSUFSWPFLAG` VARCHAR(2) 	 NULL,
  `BSUFSWITCHFLAG` VARCHAR(2) 	 NULL,
  `BSUFSETTLEMENTTYPE` VARCHAR(3) 	 NULL,
  `BSUFSIPFLAG` VARCHAR(2) 	 NULL,
  `CREATEDATE` TIMESTAMP NOT NULL DEFAULT '2017-01-01 00:00:01',
  `MODIFYDATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATEDBY` CHAR(64) NOT NULL,
  `LASTMODIFIEDBY` CHAR(64) NOT NULL,
  CONSTRAINT `PK_FCBSUF` PRIMARY KEY (`BSUFRFNUM` ASC)
)
  COMMENT='FCBSUF: BSE Suffix'

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `FCBSUF`
  ADD INDEX `IXFK_FCBSUF_FCEBSE` (`BSUFEBSERFNUM` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `FCBSUF`
  ADD CONSTRAINT `FK_FCBSUF_FCEBSE`
FOREIGN KEY (`BSUFEBSERFNUM`) REFERENCES `FCEBSE` (`EBSERFNUM`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1
;

/* Added by sumit on 08-05-2017 for FHS modification*/
ALTER TABLE `FCFHT` DROP COLUMN `FHTEXITLOAD`;
ALTER TABLE `FCFHS` ADD COLUMN `FHSEXITLOAD` DOUBLE NULL AFTER `FHSTRADEDATE`;

/* Added by sumit on 10-05-2017 for category modification*/
UPDATE `FCCTMT` SET `CTMTCTMTRFNUM`='24' WHERE `CTMTRFNUM`='24';

/*Added by sumit on 17-05-2017 for SIP module modification*/
SET FOREIGN_KEY_CHECKS=0
;

/* Drop Tables */

DROP TABLE IF EXISTS `FCSIP` CASCADE
;

DROP TABLE IF EXISTS `FCSIPH` CASCADE
;

DROP TABLE IF EXISTS `FCSIPS` CASCADE
;

DROP TABLE IF EXISTS `FCSPSM` CASCADE
;

DROP TABLE IF EXISTS `FCSST` CASCADE
;

/* Create Tables */

CREATE TABLE `FCSIP`
(
  `SIPRFNUM` BIGINT NOT NULL AUTO_INCREMENT,
  `SIPSTARTDATE` DATE NOT NULL,
  `SIPENDDATE` DATE 	 NULL,
  `SIPINSTALLMENTAMOUNT` DOUBLE NOT NULL,
  `SIPFREQUENCY` CHAR(2) NOT NULL COMMENT 'Weekly (w) Monthly (M) Quarterly (Q) Half-Yearly (H) Yearly (Y)',
  `SIPNOOFINSTALLMENTS` INT NOT NULL,
  `SIPSTATUS` CHAR(16) NOT NULL COMMENT 'Canceled Active',
  `SIPEXTERNALID` VARCHAR(16) 	 NULL,
  `SIPDEDUCTIONDAY` INT NOT NULL,
  `SIPSOTRFNUM` BIGINT NOT NULL,
  `SIPFOMTRFNUM` BIGINT NOT NULL,
  `SIPTERMINATIONDATE` DATE 	 NULL,
  `SIPREGISTRATIONDATE` DATE NOT NULL,
  `SIPRTAREGSLNO` VARCHAR(64) NOT NULL COMMENT 'RTA Registration Serial No.',
  `SIPRTATXNTYPE` VARCHAR(16) 	 NULL,
  `CREATEDATE` TIMESTAMP NOT NULL DEFAULT '2017-01-01 00:00:01',
  `MODIFYDATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATEDBY` CHAR(64) NOT NULL,
  `LASTMODIFIEDBY` CHAR(64) NOT NULL,
  CONSTRAINT `PK_FCSIP` PRIMARY KEY (`SIPRFNUM` ASC)
)
  COMMENT='FCSIP: SIP Table'

;

CREATE TABLE `FCSIPH`
(
  `SIPHRFNUM` BIGINT NOT NULL AUTO_INCREMENT,
  `SIPHSIPRFNUM` BIGINT NOT NULL,
  `SIPHSPSMFROMSTATE` BIGINT NOT NULL,
  `SIPHSPSMTOSTATE` BIGINT NOT NULL,
  `SIPHREMARK` VARCHAR(128) 	 NULL,
  `SIPHSTATECHANGEDATE` DATE NOT NULL,
  `CREATEDATE` TIMESTAMP NOT NULL DEFAULT '2017-01-01 00:00:01',
  `MODIFYDATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATEDBY` CHAR(64) NOT NULL,
  `LASTMODIFIEDBY` CHAR(10) NOT NULL,
  CONSTRAINT `PK_FCSIPH` PRIMARY KEY (`SIPHRFNUM` ASC)
)
  COMMENT='FCSIPH: SIP history'

;

CREATE TABLE `FCSIPS`
(
  `SIPSRFNUM` BIGINT NOT NULL AUTO_INCREMENT,
  `SIPSSCHEDULE` DATE NOT NULL,
  `SIPAMOUNT` DOUBLE 	 NULL,
  `SIPSSIPRFNUM` BIGINT NOT NULL,
  `CREATEDATE` TIMESTAMP NOT NULL DEFAULT '2017-01-01 00:00:01',
  `MODIFYDATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATEDBY` CHAR(64) NOT NULL,
  `LASTMODIFIEDBY` CHAR(64) NOT NULL,
  CONSTRAINT `PK_FCSIPS` PRIMARY KEY (`SIPSRFNUM` ASC)
)
  COMMENT='FCSIPS: SIP Schedule'

;

CREATE TABLE `FCSPSM`
(
  `SPSMRFNUM` BIGINT NOT NULL AUTO_INCREMENT,
  `SPSMNAME` VARCHAR(64) NOT NULL,
  `SPSMACTIVE` CHAR(2) NOT NULL,
  `SPSMDESCRIPTION` VARCHAR(256) 	 NULL,
  `SPSMDISPLAYNAME` VARCHAR(32) NOT NULL,
  `SPSMTOOLTIP` VARCHAR(128) 	 NULL,
  `CREATEDATE` TIMESTAMP NOT NULL DEFAULT '2017-01-01 00:00:01',
  `MODIFYDATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATEDBY` CHAR(64) NOT NULL,
  `LASTMODIFIEDBY` CHAR(64) NOT NULL,
  CONSTRAINT `PK_FCSPSM` PRIMARY KEY (`SPSMRFNUM` ASC)
)
  COMMENT='FCSPSM: Systematic Plans State Master'

;

CREATE TABLE `FCSST`
(
  `SSTRFNUM` BIGINT NOT NULL AUTO_INCREMENT,
  `SSTSIPRFNUM` BIGINT NOT NULL,
  `SSTCREDITAMOUNT` DOUBLE NOT NULL,
  `SSTCREDITDATE` DATE NOT NULL,
  `SSTFHSRFNUM` BIGINT NOT NULL,
  `CREATEDATE` TIMESTAMP NOT NULL DEFAULT '2017-01-01 00:00:01',
  `MODIFYDATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATEDBY` CHAR(64) NOT NULL,
  `LASTMODIFIEDBY` CHAR(64) NOT NULL,
  CONSTRAINT `PK_FCSST` PRIMARY KEY (`SSTRFNUM` ASC)
)
  COMMENT='FCSST: SIP STATEMENT TABLE'

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `FCSIPH`
  ADD INDEX `IXFK_FCSIPH_FCSIP` (`SIPHSIPRFNUM` ASC)
;

ALTER TABLE `FCSIPH`
  ADD INDEX `IXFK_FCSIPH_FCSPSM` (`SIPHSPSMFROMSTATE` ASC)
;

ALTER TABLE `FCSIPH`
  ADD INDEX `IXFK_FCSIPH_FCSPSM_02` (`SIPHSPSMTOSTATE` ASC)
;

ALTER TABLE `FCSST`
  ADD INDEX `IXFK_FCSST_FCFHS` (`SSTFHSRFNUM` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `FCSIP`
  ADD CONSTRAINT `FK_FCSIP_FCFOMT`
FOREIGN KEY (`SIPFOMTRFNUM`) REFERENCES `FCFOMT` (`FOMTRFNUM`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `FCSIP`
  ADD CONSTRAINT `FK_FCSIP_FCSOT`
FOREIGN KEY (`SIPSOTRFNUM`) REFERENCES `FCSOT` (`SOTRFNUM`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `FCSIPH`
  ADD CONSTRAINT `FK_FCSIPH_FCSIP`
FOREIGN KEY (`SIPHSIPRFNUM`) REFERENCES `FCSIP` (`SIPRFNUM`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `FCSIPH`
  ADD CONSTRAINT `FK_FCSIPH_FCSPSM`
FOREIGN KEY (`SIPHSPSMFROMSTATE`) REFERENCES `FCSPSM` (`SPSMRFNUM`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `FCSIPH`
  ADD CONSTRAINT `FK_FCSIPH_FCSPSM_02`
FOREIGN KEY (`SIPHSPSMTOSTATE`) REFERENCES `FCSPSM` (`SPSMRFNUM`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `FCSIPS`
  ADD CONSTRAINT `FK_FCSIPS_FCSIP`
FOREIGN KEY (`SIPSSIPRFNUM`) REFERENCES `FCSIP` (`SIPRFNUM`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `FCSST`
  ADD CONSTRAINT `FK_FCSST_FCFHS`
FOREIGN KEY (`SSTFHSRFNUM`) REFERENCES `FCFHS` (`FHSRFNUM`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `FCSST`
  ADD CONSTRAINT `FK_FCSST_FCSIP`
FOREIGN KEY (`SSTSIPRFNUM`) REFERENCES `FCSIP` (`SIPRFNUM`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1
;

/* Added by sagar*/
/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 18-May-2017 18:46:59 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
;

/* Drop Tables */

DROP TABLE IF EXISTS `FCOOA` CASCADE
;

/* Create Tables */

CREATE TABLE `FCOOA`
(
  `OOARFNUM` BIGINT NOT NULL AUTO_INCREMENT,
  `OOAOTPTRFNUM` BIGINT NOT NULL,
  `OOAOMTRFNUM` BIGINT NOT NULL,
  `OOAUBDRFNUM` BIGINT 	 NULL,
  `OOAPURPOSE` CHAR(32) 	 NULL COMMENT 'Purpose of OTP generation: Redemption/Verification',
  `CREATEDATE` TIMESTAMP NOT NULL DEFAULT '2017-01-01 00:00:01',
  `MODIFYDATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATEDBY` CHAR(64) NOT NULL,
  `LASTMODIFIEDBY` CHAR(64) NOT NULL,
  CONSTRAINT `PK_FCOOA` PRIMARY KEY (`OOARFNUM` ASC)
)
  COMMENT='FCOOA: OTP Order Association'

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `FCOOA`
  ADD INDEX `IXFK_FCOOA_FCOMT` (`OOAOMTRFNUM` ASC)
;

ALTER TABLE `FCOOA`
  ADD INDEX `IXFK_FCOOA_FCOTPT` (`OOAOTPTRFNUM` ASC)
;

ALTER TABLE `FCOOA`
  ADD INDEX `IXFK_FCOOA_FCUBD` (`OOAUBDRFNUM` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `FCOOA`
  ADD CONSTRAINT `FK_FCOOA_FCOMT`
FOREIGN KEY (`OOAOMTRFNUM`) REFERENCES `FCOMT` (`OMTRFNUM`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `FCOOA`
  ADD CONSTRAINT `FK_FCOOA_FCOTPT`
FOREIGN KEY (`OOAOTPTRFNUM`) REFERENCES `FCOTPT` (`OTPTRFNUM`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `FCOOA`
  ADD CONSTRAINT `FK_FCOOA_FCUBD`
FOREIGN KEY (`OOAUBDRFNUM`) REFERENCES `FCUBD` (`UBDRFNUM`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1
;


/*Added by sumit on 17-05-2017 for SIP Statement Table modification*/
ALTER TABLE `FCSST`
  CHANGE COLUMN `SSTCREDITAMOUNT` `SSTAMOUNT` DOUBLE NOT NULL ,
  CHANGE COLUMN `SSTCREDITDATE` `SSTDATE` DATE NOT NULL ,
  ADD COLUMN `SSTCREDITDEBITFLAG` VARCHAR(2) NOT NULL AFTER `SSTDATE`;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `FCBSUF`
  ADD CONSTRAINT `BSUF_EBSE_UNQ` UNIQUE (`BSUFEBSERFNUM` ASC)
;

ALTER TABLE `FCBMT` ADD COLUMN `BMTBILLERHELP` VARCHAR(2048) NULL AFTER `BMTACTIVE`,ADD COLUMN `BMTBANKTYPE` CHAR(10) NULL COMMENT 'Direct/Nodal' AFTER `BMTBILLERHELP`;

ALTER TABLE `FCBMT` CHANGE COLUMN `BMTISIPALLOWED` `BMTISIPALLOWED` CHAR(2) NOT NULL AFTER `BMTBANKTYPE`;

/*Added by sumit on 18052017 to add biller help field in bmt */

UPDATE FCBMT SET BMTBILLERHELP='https://www.axisbank.com/Demo/Axis_internet_retail_banking_demo/icon_pay%20bill.html',MODIFYDATE=CURRENT_TIMESTAMP,LASTMODIFIEDBY='admin' WHERE BMTRFNUM=11;
UPDATE FCBMT SET BMTBILLERHELP='https://payments.billdesk.com/upp/hdfcb/demo/index.htm#HDFCBillPayDemo[NewUser]/0/',MODIFYDATE=CURRENT_TIMESTAMP,LASTMODIFIEDBY='admin' WHERE BMTRFNUM=54;
UPDATE FCBMT SET BMTBILLERHELP='https://online.rblbank.com/corp/videos/payment_bill%20payment.html',MODIFYDATE=CURRENT_TIMESTAMP,LASTMODIFIEDBY='admin' WHERE BMTRFNUM=108;
UPDATE FCBMT SET BMTBILLERHELP='https://www.yesbank.in/digital-banking/online-banking/bill-payments',MODIFYDATE=CURRENT_TIMESTAMP,LASTMODIFIEDBY='admin' WHERE BMTRFNUM=182;

UPDATE FCBMT SET BMTBANKTYPE='DIRECT',MODIFYDATE=CURRENT_TIMESTAMP,LASTMODIFIEDBY='admin' WHERE BMTRFNUM=83;
UPDATE FCBMT SET BMTBANKTYPE='DIRECT',MODIFYDATE=CURRENT_TIMESTAMP,LASTMODIFIEDBY='admin' WHERE BMTRFNUM=125;
UPDATE FCBMT SET BMTBANKTYPE='DIRECT',MODIFYDATE=CURRENT_TIMESTAMP,LASTMODIFIEDBY='admin' WHERE BMTRFNUM=11;
UPDATE FCBMT SET BMTBANKTYPE='DIRECT',MODIFYDATE=CURRENT_TIMESTAMP,LASTMODIFIEDBY='admin' WHERE BMTRFNUM=58;
UPDATE FCBMT SET BMTBANKTYPE='DIRECT',MODIFYDATE=CURRENT_TIMESTAMP,LASTMODIFIEDBY='admin' WHERE BMTRFNUM=59;
UPDATE FCBMT SET BMTBANKTYPE='DIRECT',MODIFYDATE=CURRENT_TIMESTAMP,LASTMODIFIEDBY='admin' WHERE BMTRFNUM=182;
UPDATE FCBMT SET BMTBANKTYPE='NODAL',MODIFYDATE=CURRENT_TIMESTAMP,LASTMODIFIEDBY='admin' WHERE BMTRFNUM=54;
UPDATE FCBMT SET BMTBANKTYPE='NODAL',MODIFYDATE=CURRENT_TIMESTAMP,LASTMODIFIEDBY='admin' WHERE BMTRFNUM=5;
UPDATE FCBMT SET BMTBANKTYPE='NODAL',MODIFYDATE=CURRENT_TIMESTAMP,LASTMODIFIEDBY='admin' WHERE BMTRFNUM=7;
UPDATE FCBMT SET BMTBANKTYPE='NODAL',MODIFYDATE=CURRENT_TIMESTAMP,LASTMODIFIEDBY='admin' WHERE BMTRFNUM=16;
UPDATE FCBMT SET BMTBANKTYPE='NODAL',MODIFYDATE=CURRENT_TIMESTAMP,LASTMODIFIEDBY='admin' WHERE BMTRFNUM=15;
UPDATE FCBMT SET BMTBANKTYPE='NODAL',MODIFYDATE=CURRENT_TIMESTAMP,LASTMODIFIEDBY='admin' WHERE BMTRFNUM=20;
UPDATE FCBMT SET BMTBANKTYPE='NODAL',MODIFYDATE=CURRENT_TIMESTAMP,LASTMODIFIEDBY='admin' WHERE BMTRFNUM=30;
UPDATE FCBMT SET BMTBANKTYPE='NODAL',MODIFYDATE=CURRENT_TIMESTAMP,LASTMODIFIEDBY='admin' WHERE BMTRFNUM=27;
UPDATE FCBMT SET BMTBANKTYPE='NODAL',MODIFYDATE=CURRENT_TIMESTAMP,LASTMODIFIEDBY='admin' WHERE BMTRFNUM=139;
UPDATE FCBMT SET BMTBANKTYPE='NODAL',MODIFYDATE=CURRENT_TIMESTAMP,LASTMODIFIEDBY='admin' WHERE BMTRFNUM=36;
UPDATE FCBMT SET BMTBANKTYPE='NODAL',MODIFYDATE=CURRENT_TIMESTAMP,LASTMODIFIEDBY='admin' WHERE BMTRFNUM=29;
UPDATE FCBMT SET BMTBANKTYPE='NODAL',MODIFYDATE=CURRENT_TIMESTAMP,LASTMODIFIEDBY='admin' WHERE BMTRFNUM=44;
UPDATE FCBMT SET BMTBANKTYPE='NODAL',MODIFYDATE=CURRENT_TIMESTAMP,LASTMODIFIEDBY='admin' WHERE BMTRFNUM=40;
UPDATE FCBMT SET BMTBANKTYPE='NODAL',MODIFYDATE=CURRENT_TIMESTAMP,LASTMODIFIEDBY='admin' WHERE BMTRFNUM=41;
UPDATE FCBMT SET BMTBANKTYPE='NODAL',MODIFYDATE=CURRENT_TIMESTAMP,LASTMODIFIEDBY='admin' WHERE BMTRFNUM=45;
UPDATE FCBMT SET BMTBANKTYPE='NODAL',MODIFYDATE=CURRENT_TIMESTAMP,LASTMODIFIEDBY='admin' WHERE BMTRFNUM=50;
UPDATE FCBMT SET BMTBANKTYPE='NODAL',MODIFYDATE=CURRENT_TIMESTAMP,LASTMODIFIEDBY='admin' WHERE BMTRFNUM=63;
UPDATE FCBMT SET BMTBANKTYPE='NODAL',MODIFYDATE=CURRENT_TIMESTAMP,LASTMODIFIEDBY='admin' WHERE BMTRFNUM=61;
UPDATE FCBMT SET BMTBANKTYPE='NODAL',MODIFYDATE=CURRENT_TIMESTAMP,LASTMODIFIEDBY='admin' WHERE BMTRFNUM=66;
UPDATE FCBMT SET BMTBANKTYPE='NODAL',MODIFYDATE=CURRENT_TIMESTAMP,LASTMODIFIEDBY='admin' WHERE BMTRFNUM=62;
UPDATE FCBMT SET BMTBANKTYPE='NODAL',MODIFYDATE=CURRENT_TIMESTAMP,LASTMODIFIEDBY='admin' WHERE BMTRFNUM=68;
UPDATE FCBMT SET BMTBANKTYPE='NODAL',MODIFYDATE=CURRENT_TIMESTAMP,LASTMODIFIEDBY='admin' WHERE BMTRFNUM=78;
UPDATE FCBMT SET BMTBANKTYPE='NODAL',MODIFYDATE=CURRENT_TIMESTAMP,LASTMODIFIEDBY='admin' WHERE BMTRFNUM=80;
UPDATE FCBMT SET BMTBANKTYPE='NODAL',MODIFYDATE=CURRENT_TIMESTAMP,LASTMODIFIEDBY='admin' WHERE BMTRFNUM=84;
UPDATE FCBMT SET BMTBANKTYPE='NODAL',MODIFYDATE=CURRENT_TIMESTAMP,LASTMODIFIEDBY='admin' WHERE BMTRFNUM=98;
UPDATE FCBMT SET BMTBANKTYPE='NODAL',MODIFYDATE=CURRENT_TIMESTAMP,LASTMODIFIEDBY='admin' WHERE BMTRFNUM=102;
UPDATE FCBMT SET BMTBANKTYPE='NODAL',MODIFYDATE=CURRENT_TIMESTAMP,LASTMODIFIEDBY='admin' WHERE BMTRFNUM=103;
UPDATE FCBMT SET BMTBANKTYPE='NODAL',MODIFYDATE=CURRENT_TIMESTAMP,LASTMODIFIEDBY='admin' WHERE BMTRFNUM=158;
UPDATE FCBMT SET BMTBANKTYPE='NODAL',MODIFYDATE=CURRENT_TIMESTAMP,LASTMODIFIEDBY='admin' WHERE BMTRFNUM=108;
UPDATE FCBMT SET BMTBANKTYPE='NODAL',MODIFYDATE=CURRENT_TIMESTAMP,LASTMODIFIEDBY='admin' WHERE BMTRFNUM=122;
UPDATE FCBMT SET BMTBANKTYPE='NODAL',MODIFYDATE=CURRENT_TIMESTAMP,LASTMODIFIEDBY='admin' WHERE BMTRFNUM=121;
UPDATE FCBMT SET BMTBANKTYPE='NODAL',MODIFYDATE=CURRENT_TIMESTAMP,LASTMODIFIEDBY='admin' WHERE BMTRFNUM=160;
UPDATE FCBMT SET BMTBANKTYPE='NODAL',MODIFYDATE=CURRENT_TIMESTAMP,LASTMODIFIEDBY='admin' WHERE BMTRFNUM=112;
UPDATE FCBMT SET BMTBANKTYPE='NODAL',MODIFYDATE=CURRENT_TIMESTAMP,LASTMODIFIEDBY='admin' WHERE BMTRFNUM=133;
UPDATE FCBMT SET BMTBANKTYPE='NODAL',MODIFYDATE=CURRENT_TIMESTAMP,LASTMODIFIEDBY='admin' WHERE BMTRFNUM=134;
UPDATE FCBMT SET BMTBANKTYPE='NODAL',MODIFYDATE=CURRENT_TIMESTAMP,LASTMODIFIEDBY='admin' WHERE BMTRFNUM=163;
UPDATE FCBMT SET BMTBANKTYPE='NODAL',MODIFYDATE=CURRENT_TIMESTAMP,LASTMODIFIEDBY='admin' WHERE BMTRFNUM=174;
UPDATE FCBMT SET BMTBANKTYPE='NODAL',MODIFYDATE=CURRENT_TIMESTAMP,LASTMODIFIEDBY='admin' WHERE BMTRFNUM=173;
UPDATE FCBMT SET BMTBANKTYPE='NODAL',MODIFYDATE=CURRENT_TIMESTAMP,LASTMODIFIEDBY='admin' WHERE BMTRFNUM=175;
UPDATE FCBMT SET BMTBANKTYPE='NODAL',MODIFYDATE=CURRENT_TIMESTAMP,LASTMODIFIEDBY='admin' WHERE BMTRFNUM=179;
UPDATE FCBMT SET BMTBANKTYPE='NODAL',MODIFYDATE=CURRENT_TIMESTAMP,LASTMODIFIEDBY='admin' WHERE BMTRFNUM=72;
UPDATE FCBMT SET BMTBANKTYPE='NODAL',MODIFYDATE=CURRENT_TIMESTAMP,LASTMODIFIEDBY='admin' WHERE BMTRFNUM=94;
UPDATE FCBMT SET BMTBANKTYPE='NODAL',MODIFYDATE=CURRENT_TIMESTAMP,LASTMODIFIEDBY='admin' WHERE BMTRFNUM=25;
UPDATE FCBMT SET BMTBANKTYPE='NODAL',MODIFYDATE=CURRENT_TIMESTAMP,LASTMODIFIEDBY='admin' WHERE BMTRFNUM=166;
UPDATE FCBMT SET BMTBANKTYPE='NODAL',MODIFYDATE=CURRENT_TIMESTAMP,LASTMODIFIEDBY='admin' WHERE BMTRFNUM=171;


ALTER TABLE `FCBSUF` ADD COLUMN `BSUFBSEFUNDSCUTOFF` TIME NULL COMMENT 'Cutoff time for fund realization for BSE.' AFTER `BSUFBSECUTOFFTIME`;



/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 22-May-2017 16:16:32 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
;

/* Drop Tables */

DROP TABLE IF EXISTS `FCTKT` CASCADE
;

DROP TABLE IF EXISTS `FCTKTH` CASCADE
;

/* Create Tables */

CREATE TABLE `FCTKT`
(
  `TKTRFNUM` BIGINT NOT NULL AUTO_INCREMENT,
  `TKTTICKETID` VARCHAR(32) NOT NULL,
  `TKTCNDPURPOSE` BIGINT 	 NULL COMMENT 'Foreign Key to CND to get the purpose of the of the ticket creation.',
  `TKTUBDRFNUM` BIGINT 	 NULL,
  `TKTSOTRFNUM` BIGINT 	 NULL,
  `TKTREMARK` VARCHAR(256) 	 NULL,
  `TKTSTATE` VARCHAR(32) 	 NULL COMMENT 'Current State of the Ticket',
  `TKTSOURCE` VARCHAR(32) 	 NULL COMMENT 'Source of ticket generation email/API/chat etc.',
  `CREATEDATE` TIMESTAMP NOT NULL DEFAULT '2017-01-01 00:00:01',
  `MODIFYDATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATEDBY` CHAR(64) NOT NULL,
  `LASTMODIFIEDBY` CHAR(64) NOT NULL,
  CONSTRAINT `PK_FCTKT` PRIMARY KEY (`TKTRFNUM` ASC)
)
  COMMENT='FCTKT: Zendesk Ticket'

;

CREATE TABLE `FCTKTH`
(
  `TKTHRFNUM` BIGINT NOT NULL AUTO_INCREMENT,
  `TKTHFROMSTATE` VARCHAR(32) 	 NULL,
  `TKTHTOSTATE` VARCHAR(32) 	 NULL,
  `TKTHREMARK` VARCHAR(256) 	 NULL,
  `TKTHCRMRESPONSE` VARCHAR(256) 	 NULL,
  `TKTHTKTRFNUM` BIGINT NOT NULL,
  `CREATEDATE` TIMESTAMP NOT NULL DEFAULT '2017-01-01 00:00:01',
  `MODIFYDATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATEDBY` CHAR(64) NOT NULL,
  `LASTMODIFIEDBY` CHAR(64) NOT NULL,
  CONSTRAINT `PK_FCTKTH` PRIMARY KEY (`TKTHRFNUM` ASC)
)
  COMMENT='FCTKTH: Ticket History'

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `FCTKT`
  ADD INDEX `IXFK_FCTKT_FCCND` (`TKTCNDPURPOSE` ASC)
;

ALTER TABLE `FCTKT`
  ADD INDEX `IXFK_FCTKT_FCSOT` (`TKTSOTRFNUM` ASC)
;

ALTER TABLE `FCTKT`
  ADD INDEX `IXFK_FCTKT_FCUBD` (`TKTUBDRFNUM` ASC)
;

ALTER TABLE `FCTKTH`
  ADD INDEX `IXFK_FCTKTH_FCTKT` (`TKTHTKTRFNUM` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `FCTKT`
  ADD CONSTRAINT `FK_FCTKT_FCCND`
FOREIGN KEY (`TKTCNDPURPOSE`) REFERENCES `FCCND` (`CNDRFNUM`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `FCTKT`
  ADD CONSTRAINT `FK_FCTKT_FCSOT`
FOREIGN KEY (`TKTSOTRFNUM`) REFERENCES `FCSOT` (`SOTRFNUM`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `FCTKT`
  ADD CONSTRAINT `FK_FCTKT_FCUBD`
FOREIGN KEY (`TKTUBDRFNUM`) REFERENCES `FCUBD` (`UBDRFNUM`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `FCTKTH`
  ADD CONSTRAINT `FK_FCTKTH_FCTKT`
FOREIGN KEY (`TKTHTKTRFNUM`) REFERENCES `FCTKT` (`TKTRFNUM`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1
;

ALTER TABLE `FCSOPT`
  ADD INDEX `IX_FCSOPT_CREATE_DATE` (`CREATEDATE` ASC)
;

INSERT INTO FCOSTM (OSTMNAME, OSTMACTIVE, OSTMDESCRIP, OSTMDISPLAYNAME, CREATEDATE, MODIFYDATE, CREATEDBY, LASTMODIFIEDBY)
VALUES ('REDEMPTION_APPROVED', 'Y', 'Redemption Approved', 'Redemption Approved', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM');

INSERT INTO FCOSTM (OSTMNAME, OSTMACTIVE, OSTMDESCRIP, OSTMDISPLAYNAME, CREATEDATE, MODIFYDATE, CREATEDBY, LASTMODIFIEDBY)
VALUES ('PLACED_AT_AMC', 'Y', 'Placed at AMC', 'Placed at AMC', CURRENT_TIMESTAMP,
CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM');


ALTER TABLE `FCSMT` DROP COLUMN `SMTMINADDITIONAL`;

ALTER TABLE `FCSMT` ADD COLUMN `SMTRTAPURCHASECUTOFF` TIME NULL AFTER `SMTSCHEMEACTIVE`, ADD COLUMN `SMTREDEMPTIONCUTOFF` TIME NULL AFTER `SMTRTAPURCHASECUTOFF`;

/*ALTER TABLE `FCSFT` DROP COLUMN `LASTMODIFIEDBY`,DROP COLUMN `CREATEDBY`,DROP COLUMN `MODIFYDATE`,DROP COLUMN `CREATEDATE`;

ALTER TABLE `FCSFT` CHANGE COLUMN `SFTSWITCHFLAG` `SFTSWITCHINFLAG` CHAR(2) NOT NULL AFTER `SFTEXITLOADFLAG`;

ALTER TABLE `FCSFT` ADD COLUMN `SFTMINSIPPURCHASEAMT` DOUBLE NULL AFTER `SFTSIPFLAG`,ADD COLUMN `SFTMAXSIPPURCHASEAMT` DOUBLE NULL AFTER `SFTMINSIPPURCHASEAMT`,
  ADD COLUMN `SFTSIPAMTMULTIPLIER` DOUBLE NULL AFTER `SFTMAXSIPPURCHASEAMT`,
  ADD COLUMN `SFTMINSTPAMT` DOUBLE NULL AFTER `SFTSTPFLAG`,
  ADD COLUMN `SFTMAXSTPAMT` DOUBLE NULL AFTER `SFTMINSTPAMT`,
  ADD COLUMN `SFTSTPAMTMULTIPLIER` DOUBLE NULL AFTER `SFTMAXSTPAMT`,
  ADD COLUMN `SFTMINSWPAMT` DOUBLE NULL AFTER `SFTSWPFLAG`,
  ADD COLUMN `SFTMAXSWPAMT` DOUBLE NULL AFTER `SFTMINSWPAMT`,
  ADD COLUMN `SFTSWPAMTMULTIPLIER` DOUBLE NULL AFTER `SFTMAXSWPAMT`,
  ADD COLUMN `SFTMINSWITCHINAMT` DOUBLE NULL AFTER `SFTSWITCHINFLAG`,
  ADD COLUMN `SFTSWITCHOUTFLAG` CHAR(2) NULL AFTER `SFTMINSWITCHINAMT`,
  ADD COLUMN `SFTMINSWITCHOUTAMT` DOUBLE NULL AFTER `SFTSWITCHOUTFLAG`,
  ADD COLUMN `SFTSWITCHCUTOFFTIME` TIME NULL AFTER `SFTMINSWITCHOUTAMT`;*/

/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 25-May-2017 13:16:30 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
;

/* Drop Tables */

DROP TABLE IF EXISTS `FCRPA` CASCADE
;

/* Create Tables */

CREATE TABLE `FCRPA`
(
  `RPARFNUM` BIGINT NOT NULL AUTO_INCREMENT,
  `RPASOPTRFNUM` BIGINT NOT NULL,
  `RPAMINPURAMOUNT` DOUBLE 	 NULL COMMENT 'Minimum Order Amount For LumpSum Purchase.',
  `RPAMAXPURAMOUNT` DOUBLE 	 NULL COMMENT 'Minimum Order Amount For LumpSum Purchase',
  `RPAPURAMTMULTIPLIER` DOUBLE 	 NULL COMMENT 'Purchase Amount Multiplier',
  `RPAMINREDAMOUNT` DOUBLE 	 NULL,
  `RPAMAXREDAMOUNT` DOUBLE 	 NULL,
  `RPAREDAMTMULTIPLIER` DOUBLE 	 NULL,
  `RPAMINREDUNIT` DOUBLE 	 NULL,
  `RPAMAXREDUNIT` DOUBLE 	 NULL,
  `RPAREDUNITMULTIPLIER` DOUBLE 	 NULL,
  `RPAMINNFOAMOUNT` DOUBLE 	 NULL,
  `RPAMAXNFOAMOUNT` DOUBLE 	 NULL,
  `RPAMINADDINVESTAMT` DOUBLE 	 NULL COMMENT 'Minimum Additional Investment AMount',
  `RPAMINADDINVESTMULTIPLIER` DOUBLE 	 NULL COMMENT 'Minimum Additional Investment Amount Multiplier',
  `RPAISPURCHASEALLOWED` CHAR(2) NOT NULL,
  `RPAISREDEMPTIONALLOWED` CHAR(2) NOT NULL,
  `CREATEDATE` TIMESTAMP NOT NULL DEFAULT '2017-01-01 00:00:01',
  `MODIFYDATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATEDBY` CHAR(64) NOT NULL,
  `LASTMODIFIEDBY` CHAR(64) NOT NULL,
  CONSTRAINT `PK_FCRPA` PRIMARY KEY (`RPARFNUM` ASC)
)
  COMMENT='FCRMD: Redemption Purchase Amount'

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `FCRPA`
  ADD INDEX `IXFK_FCRPA_FCSOPT` (`RPASOPTRFNUM` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `FCRPA`
  ADD CONSTRAINT `FK_FCRPA_FCSOPT`
FOREIGN KEY (`RPASOPTRFNUM`) REFERENCES `FCSOPT` (`SOPTRFNUM`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1
;

ALTER TABLE `FCSOCT` ADD COLUMN `SOCTVALUEDATE` TIMESTAMP NULL AFTER `SOCTSOTRFNUM`,ADD COLUMN `SOCTVALUEDOUBLE` DOUBLE NULL AFTER `SOCTVALUEDATE`;

/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 25-May-2017 19:03:42 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
;

/* Drop Tables */

DROP TABLE IF EXISTS `FCCRT` CASCADE
;

/* Create Tables */

CREATE TABLE `FCCRT`
(
  `CRTRFNUM` BIGINT NOT NULL,
  `CRTCTMTRFNUM` BIGINT NOT NULL,
  `CRTRANKING` INT NOT NULL,
  `CRTSMTRFNUM` BIGINT NOT NULL,
  `CRTRATINGDATE` DATE NOT NULL,
  `CRTVALIDTILL` DATE NOT NULL,
  `CRTRATINGDESC` VARCHAR(1024) 	 NULL,
  `CRTRATINGMEAN` VARCHAR(50) 	 NULL,
  `CRTTOTALFUNDS` INT 	 NULL,
  `CRTREMARK` VARCHAR(512) 	 NULL,
  `CRTTOOLTIPDESC` VARCHAR(512) 	 NULL,
  `CREATEDATE` TIMESTAMP NOT NULL DEFAULT '2017-01-01 00:00:01',
  `MODIFYDATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATEDBY` CHAR(64) NOT NULL,
  `LASTMODIFIEDBY` CHAR(64) NOT NULL,
  CONSTRAINT `PK_FCCRT` PRIMARY KEY (`CRTRFNUM` ASC)
)
  COMMENT='FCCRT: Category Ranking Table'

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `FCCRT`
  ADD INDEX `IXFK_FCCRT_FCCTMT` (`CRTCTMTRFNUM` ASC)
;

ALTER TABLE `FCCRT`
  ADD INDEX `IXFK_FCCRT_FCSMT` (`CRTSMTRFNUM` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `FCCRT`
  ADD CONSTRAINT `FK_FCCRT_FCCTMT`
FOREIGN KEY (`CRTCTMTRFNUM`) REFERENCES `FCCTMT` (`CTMTRFNUM`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `FCCRT`
  ADD CONSTRAINT `FK_FCCRT_FCSMT`
FOREIGN KEY (`CRTSMTRFNUM`) REFERENCES `FCSMT` (`SMTRFNUM`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1
;

/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 25-May-2017 19:11:39 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
;

/* Drop Tables */

DROP TABLE IF EXISTS `FCSDT` CASCADE
;

/* Create Tables */

CREATE TABLE `FCSDT`
(
  `SDTRFNUM` BIGINT NOT NULL,
  `SDTFROMTIME` TIME NOT NULL,
  `SDTTOTIME` TIME NOT NULL,
  `SDTREASON` VARCHAR(512) 	 NULL,
  `SDTDATE` DATE NOT NULL,
  `SDTMESSAGE` VARCHAR(2048) NOT NULL,
  `CREATEDATE` TIMESTAMP NOT NULL DEFAULT '2017-01-01 00:00:01',
  `MODIFYDATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATEDBY` CHAR(64) NOT NULL,
  `LASTMODIFIEDBY` CHAR(64) NOT NULL,
  CONSTRAINT `PK_FCSDT` PRIMARY KEY (`SDTRFNUM` ASC)
)
  COMMENT='FCSDT: System Down Time'

;

SET FOREIGN_KEY_CHECKS=1
;

INSERT INTO `FCCND`(`CNDRFNUM`,`CNDNAME`,`CNDDESC`,`CNDGROUP`,`CNDACTIVE`,`CREATEDATE`,`MODIFYDATE`,`CREATEDBY`,`LASTMODIFIEDBY`) VALUES (1065,'Registration','Registration Ticket','TKTPURPOSE','Y',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'admin','admin');
INSERT INTO `FCCND`(`CNDRFNUM`,`CNDNAME`,`CNDDESC`,`CNDGROUP`,`CNDACTIVE`,`CREATEDATE`,`MODIFYDATE`,`CREATEDBY`,`LASTMODIFIEDBY`) VALUES (1066,'KYC','Registration Verification','TKTPURPOSE','Y',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'admin','admin');
INSERT INTO `FCCND`(`CNDRFNUM`,`CNDNAME`,`CNDDESC`,`CNDGROUP`,`CNDACTIVE`,`CREATEDATE`,`MODIFYDATE`,`CREATEDBY`,`LASTMODIFIEDBY`) VALUES (1067,'Sell','Redemption','TKTPURPOSE','Y',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'admin','admin');
INSERT INTO `FCCND`(`CNDRFNUM`,`CNDNAME`,`CNDDESC`,`CNDGROUP`,`CNDACTIVE`,`CREATEDATE`,`MODIFYDATE`,`CREATEDBY`,`LASTMODIFIEDBY`) VALUES (1068,'SIP','SIP Purchase','TKTPURPOSE','Y',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'admin','admin');
INSERT INTO `FCCND`(`CNDRFNUM`,`CNDNAME`,`CNDDESC`,`CNDGROUP`,`CNDACTIVE`,`CREATEDATE`,`MODIFYDATE`,`CREATEDBY`,`LASTMODIFIEDBY`) VALUES (1069,'Buy ','Lumpsum/Additional Purchase','TKTPURPOSE','Y',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'admin','admin');



ALTER TABLE `FCSMT` DROP COLUMN `SMTMINLUMPSUM`;

ALTER TABLE `FCSFT`
  CHANGE COLUMN `SFTSIPFLAG` `SFTSIPFLAG` CHAR(2) NOT NULL DEFAULT 'N' ,
  CHANGE COLUMN `SFTLOCKINPERIODFLAG` `SFTLOCKINPERIODFLAG` CHAR(2) NOT NULL DEFAULT 'N' ;

ALTER TABLE `FCIMT` ADD COLUMN `IMTISFALLBACKTOBSE` CHAR(2) NULL AFTER `IMTINTGRATDESCRP`;

update FCIMT set IMTISFALLBACKTOBSE = 'N' where IMTRFNUM = 1;
update FCIMT set IMTISFALLBACKTOBSE = 'Y' where IMTRFNUM = 2;

ALTER TABLE `FCBSUF` ADD COLUMN `BSUFFINALCODE` VARCHAR(16) NULL AFTER `BSUFSUFFIXCODE`;

/*Added by sumit to modify FCFPT table on 27-05-2017*/
ALTER TABLE `FCFPT`
  DROP COLUMN `FPTEXTERNALID`,
  CHANGE COLUMN `FPTSOPTRFNUM` `FPTSOPTRFNUM` BIGINT(20) NOT NULL AFTER `FPTFOMTRFNUM`,
  CHANGE COLUMN `FPTPAYOUTTYPE` `FPTRTAREFNUM` VARCHAR(32) NOT NULL AFTER `FPTSOPTRFNUM`,
  CHANGE COLUMN `FPTINVESTMENTMODE` `FPTTYPE` CHAR(2) NOT NULL AFTER `FPTRTAREFNUM`,
  CHANGE COLUMN `FPTCREDITDATE` `FPTPAYOUTDATE` DATE NOT NULL ,
  CHANGE COLUMN `FPTDECLARATIONDATE` `FPTREPORTDATE` DATE NOT NULL ,
  ADD COLUMN `FPTRTASEQUENCENO` VARCHAR(32) NOT NULL AFTER `FPTREPORTDATE`,
  ADD COLUMN `FPTREMARKS` VARCHAR(256) NULL AFTER `FPTRTASEQUENCENO`;

ALTER TABLE `FCACT` CHANGE COLUMN `ACTCONSTANTVALUE` `ACTCONSTANTVALUE` VARCHAR(2048) NOT NULL COMMENT 'Constant Value  (Login Time Duration)' ;

INSERT INTO FCACT (ACTCONSTANTNAME, ACTCONSTANTVALUE, ACTACTIVE, CREATEDATE, MODIFYDATE, CREATEDBY, LASTMODIFIEDBY)
VALUES ('BSE_BANK_DETAILS', '[{"heading":"BSE’s HDFC Bank Account Information","bankId":54,"subHeading":"(Transfer Funds via eCMS if transferring funds from HDFC Bank account)","beneficiaryName":"Indian Clearing Corporation Limited", "accountNo":"MFDICC","fullAccountNo":"MFDICC","ifsc":"HDFC0000240"},{"heading":"BSE’s ICICI Bank Account Information","bankId":58,"subHeading":"(A/C No. 000405103922 if transferring funds from ICICI Bank account)","beneficiaryName":"Indian Clearing Corporation Limited", "accountNo":"3922","fullAccountNo":"000405103922","ifsc":"ICIC0000104"}]', 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');

/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 27-May-2017 16:18:56 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `FCMER` CASCADE
;

/* Create Tables */

CREATE TABLE `FCMER`
(
	`MERRFNUM` BIGINT NOT NULL AUTO_INCREMENT,
	`MERFROMSOPTRFNUM` BIGINT NOT NULL COMMENT 'Scheme from SOPT to merge.',
	`MERTOSOPTRFNUM` BIGINT NOT NULL COMMENT 'Scheme to SOPT to merge.',
	`MERFROMDATE` DATE NOT NULL COMMENT 'Date of merger.',
	`MERREMARK` VARCHAR(128) 	 NULL,
	`CREATEDATE` TIMESTAMP NOT NULL DEFAULT '2017-01-01 00:00:01',
	`MODIFYDATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`CREATEDBY` CHAR(64) NOT NULL,
	`LASTMODIFIEDBY` CHAR(64) NOT NULL,
	CONSTRAINT `PK_FCMER` PRIMARY KEY (`MERRFNUM` ASC)
)
COMMENT='FCMER: Merger Table'

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `FCMER` 
 ADD CONSTRAINT `MER_FROMSOPT_TOSOPT` UNIQUE (`MERFROMSOPTRFNUM` ASC, `MERTOSOPTRFNUM` ASC)
;

ALTER TABLE `FCMER` 
 ADD INDEX `IXFK_FCMER_FCSOPT` (`MERFROMSOPTRFNUM` ASC)
;

ALTER TABLE `FCMER` 
 ADD INDEX `IXFK_FCMER_FCSOPT_02` (`MERTOSOPTRFNUM` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `FCMER` 
 ADD CONSTRAINT `FK_FCMER_FCSOPT`
	FOREIGN KEY (`MERFROMSOPTRFNUM`) REFERENCES `FCSOPT` (`SOPTRFNUM`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `FCMER` 
 ADD CONSTRAINT `FK_FCMER_FCSOPT_02`
	FOREIGN KEY (`MERTOSOPTRFNUM`) REFERENCES `FCSOPT` (`SOPTRFNUM`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1 
;

ALTER TABLE `FCOTPT`  ADD COLUMN `OTPISVALID` CHAR(2) NULL AFTER `OTPGATEWAYID`;
SET SQL_SAFE_UPDATES = 0;
UPDATE FCOTPT SET OTPISVALID = 'N';
ALTER TABLE `FCOTPT` CHANGE COLUMN `OTPISVALID` `OTPISVALID` CHAR(2) NOT NULL ;
SET SQL_SAFE_UPDATES = 1;

/*Added by sumit on 29052017 for Folio RTA Log tables*/
SET FOREIGN_KEY_CHECKS=0
;

/* Drop Tables */

DROP TABLE IF EXISTS `FCFRL` CASCADE
;

DROP TABLE IF EXISTS `FCRDL` CASCADE
;

/* Create Tables */

CREATE TABLE `FCFRL`
(
  `FRLRFNUM` BIGINT NOT NULL,
  `FRLRTARFNUM` BIGINT 	 NULL,
  `FRLFILEPATH` VARCHAR(512) NOT NULL COMMENT 'Processed File Path',
  `FRLREVERSALRFNUM` BIGINT 	 NULL COMMENT 'Reversal Rf Num in case of Reversal',
  `FRLPROCESSDATE` DATE NOT NULL COMMENT 'File Processing Date',
  `FRLFILEBACKUPPATH` VARCHAR(512) 	 NULL COMMENT 'File Backup Path where the file has been moved',
  `FRLLOGFILEPATH` VARCHAR(512) 	 NULL COMMENT 'Log file Path where the file has been moved',
  `CREATEDATE` TIMESTAMP NOT NULL DEFAULT '2017-01-01 00:00:01',
  `MODIFYDATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATEDBY` CHAR(64) NOT NULL,
  `LASTMODIFIEDBY` CHAR(64) NOT NULL,
  CONSTRAINT `PK_FCFRL` PRIMARY KEY (`FRLRFNUM` ASC)
)
  COMMENT='FCFRL: Folio RTA Log'

;

CREATE TABLE `FCRDL`
(
  `RDLRFNUM` BIGINT NOT NULL,
  `RDLFRLRFNUM` BIGINT NOT NULL,
  `RDLRTARFNUM` BIGINT 	 NULL,
  `RDLRTATXNNO` VARCHAR(128) NOT NULL,
  `RDLORDERREF` VARCHAR(128) 	 NULL,
  `RDLRTASYSTEMATICREF` VARCHAR(128) 	 NULL COMMENT 'RTA Reference For Systematic Plans',
  `RDLSTATUS` VARCHAR(10) NOT NULL,
  `RDLREMARK` VARCHAR(512) 	 NULL,
  `CREATEDATE` TIMESTAMP NOT NULL DEFAULT '2017-01-01 00:00:01',
  `MODIFYDATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATEDBY` CHAR(64) NOT NULL,
  `LASTMODIFIEDBY` CHAR(64) NOT NULL,
  CONSTRAINT `PK_FCRDL` PRIMARY KEY (`RDLRFNUM` ASC)
)
  COMMENT='FCRDL: RTA DATA Log'

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `FCFRL`
  ADD INDEX `IXFK_FCFRL_FCFRL` (`FRLREVERSALRFNUM` ASC)
;

ALTER TABLE `FCFRL`
  ADD INDEX `IXFK_FCFRL_FCRTA` (`FRLRTARFNUM` ASC)
;

ALTER TABLE `FCRDL`
  ADD INDEX `IXFK_FCRDL_FCRTA` (`RDLRTARFNUM` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `FCFRL`
  ADD CONSTRAINT `FK_FCFRL_FCFRL`
FOREIGN KEY (`FRLREVERSALRFNUM`) REFERENCES `FCFRL` (`FRLRFNUM`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `FCFRL`
  ADD CONSTRAINT `FK_FCFRL_FCRTA`
FOREIGN KEY (`FRLRTARFNUM`) REFERENCES `FCRTA` (`RTARFNUM`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `FCRDL`
  ADD CONSTRAINT `FK_FCRDL_FCRTA`
FOREIGN KEY (`RDLRTARFNUM`) REFERENCES `FCRTA` (`RTARFNUM`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `FCRDL`
  ADD CONSTRAINT `FK_FCRDL_FCFRL`
FOREIGN KEY (`RDLFRLRFNUM`) REFERENCES `FCFRL` (`FRLRFNUM`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `FCFRL`
  CHANGE COLUMN `FRLRFNUM` `FRLRFNUM` BIGINT(20) NOT NULL AUTO_INCREMENT ;


ALTER TABLE `FCRDL`
  CHANGE COLUMN `RDLRFNUM` `RDLRFNUM` BIGINT(20) NOT NULL AUTO_INCREMENT ;


SET FOREIGN_KEY_CHECKS=1
;

ALTER TABLE `FCOTPT`
  CHANGE COLUMN `OTPREQTIME` `OTPTREQTIME` TIMESTAMP NOT NULL DEFAULT '2017-01-01 00:00:01' COMMENT 'OTP Request Time' ,
  CHANGE COLUMN `OTPVALIDITYTIME` `OTPTVALIDITYTIME` TIMESTAMP NOT NULL DEFAULT '2017-01-01 00:00:01' COMMENT 'OTP Validity Time (Time instant Post the OTP Received)' ,
  CHANGE COLUMN `OTPSTATUS` `OTPTSTATUS` CHAR(10) NULL DEFAULT NULL COMMENT 'Delivered (D) Pending (P) Sent (S) Not Delivered (ND)' ,
  CHANGE COLUMN `OTPMESSAGEID` `OTPTMESSAGEID` CHAR(64) NULL DEFAULT NULL COMMENT 'Message Id' ,
  CHANGE COLUMN `OTPGATEWAYID` `OTPTGATEWAYID` CHAR(2) NOT NULL COMMENT 'Service Provider (Airtel/Vodafone)' ,
  CHANGE COLUMN `OTPISVALID` `OTPTISVALID` CHAR(2) NOT NULL ;

/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 29-May-2017 19:56:50 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
;

/* Drop Tables */

DROP TABLE IF EXISTS `FCBSAT` CASCADE
;

/* Create Tables */

CREATE TABLE `FCBSAT`
(
  `BSATRFNUM` BIGINT NOT NULL AUTO_INCREMENT,
  `BSATAIPDAY` VARCHAR(128) NOT NULL,
  `BSATBSERFNUM` BIGINT NOT NULL,
  `BSATFREQUENCY` CHAR(2) NOT NULL,
  `BSATMINTENURE` INT NOT NULL,
  `BSATTYPE` CHAR(4) NOT NULL,
  `BSATMINAMOUNT` INT NOT NULL,
  `BSATADDITIONALAMT` INT NOT NULL,
  `BSATMAXAMOUNT` BIGINT NOT NULL,
  `BSATMAXTENURE` BIGINT NOT NULL,
  `BSATMULTIPLIER` INT NOT NULL,
  `BSATIDENTIFIER` CHAR(10) NOT NULL,
  `BSATMINIMUMGAP` INT NOT NULL COMMENT 'No. of Days ',
  `BSATMAXIMUMGAP` INT NOT NULL,
  `BSATINSTALLMENTGAP` INT NOT NULL,
  `BSATMININSTALLMENTNOS` INT NOT NULL,
  `BSATMAXINSTALLMENTNOS` INT NOT NULL,
  `CREATEDATE` TIMESTAMP NOT NULL DEFAULT '2017-01-01 00:00:01',
  `MODIFYDATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATEDBY` CHAR(64) NOT NULL,
  `LASTMODIFIEDBY` CHAR(64) NOT NULL,
  CONSTRAINT `PK_FCBSAT` PRIMARY KEY (`BSATRFNUM` ASC)
)
  COMMENT='FCBSAT: BSE Systematic Amount Table'

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `FCBSAT`
  ADD INDEX `IXFK_FCBSAT_FCBSE` (`BSATBSERFNUM` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `FCBSAT`
  ADD CONSTRAINT `FK_FCBSAT_FCBSE`
FOREIGN KEY (`BSATBSERFNUM`) REFERENCES `FCBSE` (`BSERFNUM`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1
;



ALTER TABLE `FCFHS`
  DROP COLUMN `CREATEDBY`;

ALTER TABLE `FCFHS`
  ADD COLUMN `FHSFRLRFNUM` BIGINT(20) NOT NULL AFTER `LASTMODIFIEDBY`;

ALTER TABLE `FCFHS`
  ADD INDEX `FK_FCFHS_FCFRL` (`FHSFRLRFNUM` ASC);

ALTER TABLE `FCFHS`
  ADD CONSTRAINT `FK_FCFHS_FCFRL`
FOREIGN KEY (`FHSFRLRFNUM`)
REFERENCES `FCFRL` (`FRLRFNUM`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;


ALTER TABLE `FCFPT`
  ADD COLUMN `FPTFRLRFNUM` BIGINT(20) NOT NULL AFTER `LASTMODIFIEDBY`;

ALTER TABLE `FCFPT`
  ADD INDEX `FK_FCFPT_FCFRL` (`FPTFRLRFNUM` ASC);

ALTER TABLE `FCFPT`
  ADD CONSTRAINT `FK_FCFPT_FCFRL`
FOREIGN KEY (`FPTFRLRFNUM`)
REFERENCES `FCFRL` (`FRLRFNUM`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

/*Added by sumit on 30052017 for FHT modification*/
ALTER TABLE `FCFHT`
  ADD COLUMN `FHTINITIALUNITS` DOUBLE NOT NULL AFTER `FHTHOLDINGUNITS`;

ALTER TABLE `FCOTPT`
  ADD COLUMN `OTPTIPADDRESS` VARCHAR(64) NULL AFTER `OTPTISVALID`;

ALTER TABLE `FCUACT`
  ADD COLUMN `UACTIPADDRESS` VARCHAR(64) NULL AFTER `UACTISUSED`;

ALTER TABLE `FCOSTM`
  ADD COLUMN `OSTMTOSTATES` VARCHAR(128) NULL AFTER `OSTMTOOLTIP`;


/*Added by sumit on 31052017 for FHS modification*/
ALTER TABLE `FCFHS`
  DROP COLUMN `LASTMODIFIEDBY`,
  DROP COLUMN `MODIFYDATE`,
  ADD COLUMN `FHSEXTERNALORDERID` CHAR(32) NOT NULL AFTER `FHSFRLRFNUM`;


/*Added by sumit on 31052017 for CND modification*/
ALTER TABLE `FCCND`
  CHANGE COLUMN `CNDRFNUM` `CNDRFNUM` BIGINT(20) NOT NULL COMMENT 'Primary Key' ;

/* Added by Paresh on 31052017 for BSL entry in IMT & SIA*/
INSERT INTO `FCIMT` (`IMTRFNUM`, `IMTINTGRATNAME`, `IMTINTGRATACTIVE`, `IMTINTGRATDESCRP`, `IMTISFALLBACKTOBSE`, `CREATEDBY`, `LASTMODIFIEDBY`) VALUES (3, 'BSL', 'Y', 'Birla Sun Life', 'Y', 'admin', 'admin');
INSERT INTO `FCSIA` (`SIARFNUM`, `SIASMTRFNUM`, `SIAIMTRFNUM`, `SIATXNTYPE`, `CREATEDBY`, `LASTMODIFIEDBY`) VALUES (2, '1198', '3', 'R', 'admin', 'admin');

/* Added by Paresh on 31052017 for DRQP entries for Reliance */
INSERT INTO `FCDRQP` (`DRQPIMTRFNUM`, `DRQPPARANAME`, `DRQPPARAVALUE`, `CREATEDBY`, `LASTMODIFIEDBY`) VALUES (2, 'fund', 'RMF', 'admin', 'admin');
INSERT INTO `FCDRQP` (`DRQPIMTRFNUM`, `DRQPPARANAME`, `DRQPPARAVALUE`, `CREATEDBY`, `LASTMODIFIEDBY`) VALUES (2, 'scheme', 'LF', 'admin', 'admin');
INSERT INTO `FCDRQP` (`DRQPIMTRFNUM`, `DRQPPARANAME`, `DRQPPARAVALUE`, `CREATEDBY`, `LASTMODIFIEDBY`) VALUES (2, 'plan', 'IG', 'admin', 'admin');
INSERT INTO `FCDRQP` (`DRQPIMTRFNUM`, `DRQPPARANAME`, `DRQPPARAVALUE`, `CREATEDBY`, `LASTMODIFIEDBY`) VALUES (2, 'options', 'G', 'admin', 'admin');
INSERT INTO `FCDRQP` (`DRQPIMTRFNUM`, `DRQPPARANAME`, `DRQPPARAVALUE`, `CREATEDBY`, `LASTMODIFIEDBY`) VALUES (2, 'Tpin', 'A', 'admin', 'admin');
INSERT INTO `FCDRQP` (`DRQPIMTRFNUM`, `DRQPPARANAME`, `DRQPPARAVALUE`, `CREATEDBY`, `LASTMODIFIEDBY`) VALUES (2, 'Mstatus', 'Insta', 'admin', 'admin');
INSERT INTO `FCDRQP` (`DRQPIMTRFNUM`, `DRQPPARANAME`, `DRQPPARAVALUE`, `CREATEDBY`, `LASTMODIFIEDBY`) VALUES (2, 'oldihno', '0', 'admin', 'admin');
INSERT INTO `FCDRQP` (`DRQPIMTRFNUM`, `DRQPPARANAME`, `DRQPPARAVALUE`, `CREATEDBY`, `LASTMODIFIEDBY`) VALUES (2, 'branch', 'SQ99', 'admin', 'admin');
INSERT INTO `FCDRQP` (`DRQPIMTRFNUM`, `DRQPPARANAME`, `DRQPPARAVALUE`, `CREATEDBY`, `LASTMODIFIEDBY`) VALUES (2, 'deviceid', 'PARTNERAPI', 'admin', 'admin');
INSERT INTO `FCDRQP` (`DRQPIMTRFNUM`, `DRQPPARANAME`, `DRQPPARAVALUE`, `CREATEDBY`, `LASTMODIFIEDBY`) VALUES (2, 'appVersion', '1.0.1', 'admin', 'admin');
INSERT INTO `FCDRQP` (`DRQPIMTRFNUM`, `DRQPPARANAME`, `DRQPPARAVALUE`, `CREATEDBY`, `LASTMODIFIEDBY`) VALUES (2, 'appName', 'FINCASH', 'admin', 'admin');
INSERT INTO `FCDRQP` (`DRQPIMTRFNUM`, `DRQPPARANAME`, `DRQPPARAVALUE`, `CREATEDBY`, `LASTMODIFIEDBY`) VALUES (2, 'apikey', '2665ae4f-0583-4872-a8d1-07815cb938ce', 'admin', 'admin');
INSERT INTO `FCDRQP` (`DRQPIMTRFNUM`, `DRQPPARANAME`, `DRQPPARAVALUE`, `CREATEDBY`, `LASTMODIFIEDBY`) VALUES (2, 'arncode', 'ARN-112358', 'admin', 'admin');
INSERT INTO `FCDRQP` (`DRQPIMTRFNUM`, `DRQPPARANAME`, `DRQPPARAVALUE`, `CREATEDBY`, `LASTMODIFIEDBY`) VALUES (2, 'Fname', '', 'admin', 'admin');
INSERT INTO `FCDRQP` (`DRQPIMTRFNUM`, `DRQPPARANAME`, `DRQPPARAVALUE`, `CREATEDBY`, `LASTMODIFIEDBY`) VALUES (2, 'Mname', '', 'admin', 'admin');
INSERT INTO `FCDRQP` (`DRQPIMTRFNUM`, `DRQPPARANAME`, `DRQPPARAVALUE`, `CREATEDBY`, `LASTMODIFIEDBY`) VALUES (2, 'Lname', '', 'admin', 'admin');
INSERT INTO `FCDRQP` (`DRQPIMTRFNUM`, `DRQPPARANAME`, `DRQPPARAVALUE`, `CREATEDBY`, `LASTMODIFIEDBY`) VALUES (2, 'Cuttime', '', 'admin', 'admin');
INSERT INTO `FCDRQP` (`DRQPIMTRFNUM`, `DRQPPARANAME`, `DRQPPARAVALUE`, `CREATEDBY`, `LASTMODIFIEDBY`) VALUES (2, 'pangno', '', 'admin', 'admin');
INSERT INTO `FCDRQP` (`DRQPIMTRFNUM`, `DRQPPARANAME`, `DRQPPARAVALUE`, `CREATEDBY`, `LASTMODIFIEDBY`) VALUES (2, 'proxybranch', '', 'admin', 'admin');
INSERT INTO `FCDRQP` (`DRQPIMTRFNUM`, `DRQPPARANAME`, `DRQPPARAVALUE`, `CREATEDBY`, `LASTMODIFIEDBY`) VALUES (2, 'userid', '', 'admin', 'admin');

/*Added by sumit for application constant on 09-06-2017*/
INSERT INTO FCACT (ACTRFNUM,ACTCONSTANTNAME, ACTCONSTANTVALUE, ACTACTIVE, CREATEDATE, MODIFYDATE, CREATEDBY, LASTMODIFIEDBY) VALUES (11,'MSTAR_ACCESS_CODE', 'xhxm94ugehapq72sdrtnhzyfmeyaakku', 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin');
