
/* Added by Paresh for adding IP in document master table */
/*ALTER TABLE `FCDMT`
ADD COLUMN `DMTUPLOADIP` VARCHAR(32) NULL DEFAULT NULL AFTER `DMTDOCVALIDITY`;*/

/*Added by sumit to add folio merger table on  07-07-2017*/
SET FOREIGN_KEY_CHECKS=0
;

/* Drop Tables */

DROP TABLE IF EXISTS `FCFOME` CASCADE
;

/* Create Tables */

CREATE TABLE `FCFOME`
(
  `FOMERFNUM` BIGINT NOT NULL AUTO_INCREMENT,
  `FOMEFHTRFNUM` BIGINT NOT NULL,
  `FOMEFOMTRFNUM` BIGINT NOT NULL,
  `FOMERTAREFNUM` VARCHAR(32) NOT NULL,
  `FOMERTASEQUENCENO` VARCHAR(32) NOT NULL,
  `FOMEPOSTDATE` DATE NOT NULL,
  `FOMETRANSACTIONMODE` CHAR(2) NOT NULL,
  `FOMETRANSACTIONTYPE` CHAR(8) NOT NULL,
  `CREATEDATE` TIMESTAMP NOT NULL DEFAULT '2017-01-01 00:00:01',
  `MODIFYDATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATEDBY` CHAR(64) NOT NULL,
  `LASTMODIFIEDBY` CHAR(64) NOT NULL,
  CONSTRAINT `PK_FCFOME` PRIMARY KEY (`FOMERFNUM` ASC)
)
  COMMENT='FCFOME: Folio Merger Table'

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `FCFOME`
  ADD INDEX `IXFK_FCFOME_FCFHT` (`FOMEFHTRFNUM` ASC)
;

ALTER TABLE `FCFOME`
  ADD INDEX `IXFK_FCFOME_FCFOMT` (`FOMEFOMTRFNUM` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `FCFOME`
  ADD CONSTRAINT `FK_FCFOME_FCFHT`
FOREIGN KEY (`FOMEFHTRFNUM`) REFERENCES `FCFHT` (`FHTRFNUM`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `FCFOME`
  ADD CONSTRAINT `FK_FCFOME_FCFOMT`
FOREIGN KEY (`FOMEFOMTRFNUM`) REFERENCES `FCFOMT` (`FOMTRFNUM`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1
;

/*Added by sumit to modify FCFOMT table on  07-07-2017*/
ALTER TABLE `FCFOMT`
  ADD COLUMN `FOMTMERGEDRFNUM` BIGINT(20) NULL AFTER `LASTMODIFIEDBY`,
  ADD INDEX `FK_FCFOMT_FCFOMT_idx` (`FOMTMERGEDRFNUM` ASC);
ALTER TABLE `FCFOMT`
  ADD CONSTRAINT `FK_FCFOMT_FCFOMT`
FOREIGN KEY (`FOMTMERGEDRFNUM`)
REFERENCES `FCFOMT` (`FOMTRFNUM`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;